# sbatch completion script generated by https://github.com/adaszko/complgen

if [[ ${BASH_VERSINFO[0]} -lt 4 ]]; then
    echo "This completion script requires bash 4.0 or newer (current is $BASH_VERSION)"
    exit 1
fi

_sbatch_cmd_0 () {
    sacctmgr show account -nP format=account
}

_sbatch_cmd_1 () {
    compgen -A file -- "$1"
}

_sbatch_cmd_2 () {
    squeue -u $USER -ho '%A'
}

_sbatch_cmd_3 () {
    sinfo -ho "%G" | sed 's/([^)]*)//g' | tr ':' '\n' | grep -v '^[0-9]' | sort -u
}

_sbatch_cmd_4 () {
    squeue -u $USER -ho '%j'
}

_sbatch_cmd_5 () {
    scontrol show lic
}

_sbatch_cmd_6 () {
    sacctmgr show cluster -nP format=clusters
}

_sbatch_cmd_7 () {
    sacctmgr show user -nP format=user
}

_sbatch_cmd_8 () {
    sinfo -ho %P
}

_sbatch_cmd_9 () {
    sacctmgr show qos -nP format=name
}

_sbatch_cmd_10 () {
    squeue -u $USER -ho '%w'
}

_sbatch_cmd_11 () {
    compgen -c
}

_sbatch_cmd_12 () {
    sinfo -ho %f
}

_sbatch_cmd_13 () {
    sacctmgr show reservation -nP format=name
}

_sbatch_cmd_14 () {
    sinfo -ho %n
}

_sbatch_cmd_15 () {
    find -L . \
-path '*/.*' -prune -o \
-path '*/_*' -prune -o \
-path '*/*asset*' -prune -o \
-path '*/*cache*' -prune -o \
-path '*/data*' -prune -o \
-path '*/doc*' -prune -o \
-path '*/lib*' -prune -o \
-path '*/*log*' -prune -o \
-path '*/node*' -prune -o \
-path '*/saves' -prune -o \
-path '*/wandb' -prune -o \
-type f -name '*.sbatch' -print
}

_sbatch_subword_0 () {
    local -a literals=("--array=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_1 () {
    local -a literals=("--account=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([0]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="0")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_2 () {
    local -a literals=("--bb=" "spec")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_3 () {
    local -a literals=("--bbf=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([1]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="1")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_4 () {
    local -a literals=("YYYY-MM-DD" "MM/DD/YY" "--begin=" "minutes" "seconds" "THH:MM" "MMDDYY" "HH:MM" "weeks" "hours" "days" ":SS" "now" "+1")
    local -A literal_transitions=()
    literal_transitions[1]="([12]=2 [7]=3 [6]=4 [1]=4 [0]=5)"
    literal_transitions[5]="([5]=3)"
    literal_transitions[3]="([11]=4)"
    literal_transitions[2]="([13]=6)"
    literal_transitions[0]="([2]=1)"
    literal_transitions[6]="([4]=4 [3]=4 [9]=4 [10]=4 [8]=4)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="12 7 6 1 0" [5]="5" [3]="11" [2]="13" [0]="2" [6]="4 3 9 10 8")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_5 () {
    local -a literals=("--comment=" "...")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_6 () {
    local -a literals=("Conservative" "Performance" "--cpu-freq=" "UserSpace" "SchedUtil" "PowerSave" "OnDemand" "highm1" "medium" "high" "low" ":" "-" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([22]=2 [21]=3 [20]=3 [19]=3 [18]=3 [17]=3 [16]=3 [15]=3 [14]=3 [13]=3 [10]=2 [8]=2 [9]=2 [7]=2)"
    literal_transitions[2]="([12]=4 [11]=5)"
    literal_transitions[0]="([2]=1)"
    literal_transitions[7]="([11]=5)"
    literal_transitions[5]="([0]=6 [6]=6 [1]=6 [5]=6 [4]=6 [3]=6)"
    literal_transitions[4]="([22]=7 [21]=8 [20]=8 [19]=8 [18]=8 [17]=8 [16]=8 [15]=8 [14]=8 [13]=8 [8]=7 [9]=7 [7]=7)"
    literal_transitions[3]="([22]=3 [21]=3 [20]=3 [19]=3 [18]=3 [17]=3 [16]=3 [15]=3 [14]=3 [13]=3 [12]=4 [11]=5)"
    literal_transitions[8]="([22]=8 [21]=8 [20]=8 [19]=8 [18]=8 [17]=8 [16]=8 [15]=8 [14]=8 [13]=8 [11]=5)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="22 21 20 19 18 17 16 15 14 13 10 8 9 7" [2]="12 11" [0]="2" [7]="11" [5]="0 6 1 5 4 3" [4]="22 21 20 19 18 17 16 15 14 13 8 9 7" [3]="22 21 20 19 18 17 16 15 14 13 12 11" [8]="22 21 20 19 18 17 16 15 14 13 11")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_7 () {
    local -a literals=("--cpus-per-task=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_8 () {
    local -a literals=("--dependency=" "afternotok" "aftercorr" "afterany" "afterok" "after" ":")
    local -A literal_transitions=()
    literal_transitions[1]="([5]=2 [3]=2 [4]=2 [2]=2 [1]=2)"
    literal_transitions[4]="([6]=3)"
    literal_transitions[2]="([6]=3)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[3]="([2]=4)"
    local -A literal_transitions_level_0=([1]="5 3 4 2 1" [4]="6" [2]="6" [0]="0")
    local -A commands_level_0=([3]="2")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_9 () {
    local -a literals=("afternotok" "aftercorr" "afterany" "afterok" "after" ":" ",")
    local -A literal_transitions=()
    literal_transitions[1]="([4]=2 [2]=2 [3]=2 [1]=2 [0]=2)"
    literal_transitions[4]="([5]=3)"
    literal_transitions[2]="([5]=3)"
    literal_transitions[0]="([6]=1)"
    local -A command_transitions=()
    command_transitions[3]="([2]=4)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="4 2 3 1 0" [4]="5" [2]="5" [0]="6")
    local -A commands_level_0=([3]="2")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_10 () {
    local -a literals=("--deadline=" "YYYY-MM-DD" "MM/DD/YY" "minutes" "seconds" "THH:MM" "MMDDYY" "HH:MM" "weeks" "hours" "days" ":SS" "now" "+1")
    local -A literal_transitions=()
    literal_transitions[1]="([12]=2 [7]=3 [6]=4 [2]=4 [1]=5)"
    literal_transitions[5]="([5]=3)"
    literal_transitions[3]="([11]=4)"
    literal_transitions[2]="([13]=6)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[6]="([4]=4 [3]=4 [9]=4 [10]=4 [8]=4)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="12 7 6 2 1" [5]="5" [3]="11" [2]="13" [0]="0" [6]="4 3 9 10 8")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_11 () {
    local -a literals=("--delay-boot=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_12 () {
    local -a literals=("--chdir=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([1]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="1")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_13 () {
    local -a literals=("--error=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([1]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="1")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_14 () {
    local -a literals=("--export=" ",ENVVAR" "NONE" "NIL" "ALL")
    local -A literal_transitions=()
    literal_transitions[1]="([4]=2 [2]=3 [3]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[2]="([1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="4 2 3" [0]="0" [2]="1")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_15 () {
    local -a literals=("--gid=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_16 () {
    local -a literals=("--gres=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([3]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="3")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_17 () {
    local -a literals=("multiple-tasks-per-sharing" "one-task-per-sharing" "allow-task-sharing" "enforce-binding" "disable-binding" "--gres-flags=")
    local -A literal_transitions=()
    literal_transitions[1]="([2]=2 [0]=2 [4]=2 [3]=2 [1]=2)"
    literal_transitions[0]="([5]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="2 0 4 3 1" [0]="5")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_18 () {
    local -a literals=("--input=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([1]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="1")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_19 () {
    local -a literals=("--job-name=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([4]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="4")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_20 () {
    local -a literals=("--licenses=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([5]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="5")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_21 () {
    local -a literals=("9" "8" "7" "6" "5" "4" "3" "2" "1" "0" ":" ",")
    local -A literal_transitions=()
    literal_transitions[5]="([9]=5 [8]=5 [7]=5 [6]=5 [5]=5 [4]=5 [3]=5 [2]=5 [1]=5 [0]=5)"
    literal_transitions[3]="([9]=4 [8]=5 [7]=5 [6]=5 [5]=5 [4]=5 [3]=5 [2]=5 [1]=5 [0]=5)"
    literal_transitions[2]="([10]=3)"
    literal_transitions[0]="([11]=1)"
    local -A command_transitions=()
    command_transitions[1]="([5]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([5]="9 8 7 6 5 4 3 2 1 0" [3]="9 8 7 6 5 4 3 2 1 0" [2]="10" [0]="11")
    local -A commands_level_0=([1]="5")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_22 () {
    local -a literals=("--clusters=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([6]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="6")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_23 () {
    local -a literals=("--container=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([1]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="1")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_24 () {
    local -a literals=("--container-id=" "...")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_25 () {
    local -a literals=("--distribution=" "arbitrary" "cyclic" "plane" "block")
    local -A literal_transitions=()
    literal_transitions[1]="([4]=2 [2]=2 [1]=2 [3]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="4 2 1 3" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_26 () {
    local -a literals=("TIME_LIMIT_50" "TIME_LIMIT_80" "TIME_LIMIT_90" "--mail-type=" "ARRAY_TASKS" "TIME_LIMIT" "STAGE_OUT" "REQUEUE" "BEGIN" "FAIL" "NONE" "ALL" "END")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [8]=2 [12]=2 [9]=2 [11]=2 [7]=2 [6]=2 [5]=2 [2]=2 [1]=2 [0]=2 [4]=2)"
    literal_transitions[0]="([3]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="10 8 12 9 11 7 6 5 2 1 0 4" [0]="3")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_27 () {
    local -a literals=("--mail-user=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([7]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="7")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_28 () {
    local -a literals=("--mcs-label=" "...")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_29 () {
    local -a literals=("--ntasks=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_30 () {
    local -a literals=("--nice" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0" "=")
    local -A literal_transitions=()
    literal_transitions[1]="([11]=2)"
    literal_transitions[4]="([10]=4 [9]=4 [8]=4 [7]=4 [6]=4 [5]=4 [4]=4 [3]=4 [2]=4 [1]=4)"
    literal_transitions[2]="([10]=3 [9]=4 [8]=4 [7]=4 [6]=4 [5]=4 [4]=4 [3]=4 [2]=4 [1]=4)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="11" [4]="10 9 8 7 6 5 4 3 2 1" [2]="10 9 8 7 6 5 4 3 2 1" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_31 () {
    local -a literals=("--ntasks-per-node=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_32 () {
    local -a literals=("--nodes=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_33 () {
    local -a literals=("--output=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([1]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="1")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_34 () {
    local -a literals=("--partition=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([8]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="8")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_35 () {
    local -a literals=("--power=" "...")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_36 () {
    local -a literals=("--priority=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_37 () {
    local -a literals=("filesystem" "--profile=" "network" "energy" "task" "none" "all" ",")
    local -A literal_transitions=()
    literal_transitions[1]="([6]=2 [5]=2 [4]=2 [3]=2 [2]=2 [0]=2 [7]=3)"
    literal_transitions[4]="([7]=3)"
    literal_transitions[3]="([4]=4 [3]=4 [2]=4 [0]=4)"
    literal_transitions[0]="([1]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="6 5 4 3 2 0" [0]="1")
    local -A literal_transitions_level_1=([1]="7" [4]="7" [3]="4 3 2 0")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_38 () {
    local -a literals=("--propagate" "=rlimits")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_39 () {
    local -a literals=("--qos=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([9]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="9")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_40 () {
    local -a literals=("--core-spec=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_41 () {
    local -a literals=("SIGWAITING" "SIGVTALRM" "--signal=" "SIGWINCH" "SIGXFSZ" "SIGXCPU" "SIGPROF" "SIGTTOU" "SIGTTIN" "SIGCONT" "SIGTSTP" "SIGSTOP" "SIGPOLL" "SIGCHLD" "SIGUSR2" "SIGUSR1" "SIGTERM" "SIGALRM" "SIGPIPE" "SIGSEGV" "SIGKILL" "SIGABRT" "SIGTRAP" "SIGQUIT" "SIGAIO" "SIGLWP" "SIGURG" "SIGPWR" "SIGCLD" "SIGSYS" "SIGBUS" "SIGFPE" "SIGEMT" "SIGIOT" "SIGILL" "SIGINT" "SIGHUP" "SIGIO" "60" "34" "33" "32" "31" "30" "29" "28" "27" "26" "25" "24" "23" "22" "21" "20" "19" "18" "17" "16" "15" "14" "13" "12" "11" "10" "R:" "h" "m" "s" "9" "8" "7" "6" "5" "4" "3" "2" "1")
    local -A literal_transitions=()
    literal_transitions[1]="([64]=2 [76]=3 [36]=3 [75]=3 [35]=3 [74]=3 [23]=3 [73]=3 [34]=3 [72]=3 [22]=3 [71]=3 [33]=3 [21]=3 [70]=3 [32]=3 [69]=3 [31]=3 [68]=3 [20]=3 [63]=3 [30]=3 [62]=3 [19]=3 [61]=3 [29]=3 [60]=3 [18]=3 [59]=3 [17]=3 [58]=3 [16]=3 [57]=3 [15]=3 [56]=3 [14]=3 [55]=3 [28]=3 [13]=3 [54]=3 [27]=3 [53]=3 [3]=3 [52]=3 [26]=3 [51]=3 [12]=3 [37]=3 [50]=3 [11]=3 [49]=3 [10]=3 [48]=3 [9]=3 [47]=3 [8]=3 [46]=3 [7]=3 [45]=3 [1]=3 [44]=3 [6]=3 [43]=3 [5]=3 [42]=3 [4]=3 [41]=3 [0]=3 [40]=3 [25]=3 [39]=3 [24]=3)"
    literal_transitions[4]="([67]=5 [66]=5 [65]=5)"
    literal_transitions[3]="([38]=4)"
    literal_transitions[2]="([76]=3 [36]=3 [75]=3 [35]=3 [74]=3 [23]=3 [73]=3 [34]=3 [72]=3 [22]=3 [71]=3 [33]=3 [21]=3 [70]=3 [32]=3 [69]=3 [31]=3 [68]=3 [20]=3 [63]=3 [30]=3 [62]=3 [19]=3 [61]=3 [29]=3 [60]=3 [18]=3 [59]=3 [17]=3 [58]=3 [16]=3 [57]=3 [15]=3 [56]=3 [14]=3 [55]=3 [28]=3 [13]=3 [54]=3 [27]=3 [53]=3 [3]=3 [52]=3 [26]=3 [51]=3 [12]=3 [37]=3 [50]=3 [11]=3 [49]=3 [10]=3 [48]=3 [9]=3 [47]=3 [8]=3 [46]=3 [7]=3 [45]=3 [1]=3 [44]=3 [6]=3 [43]=3 [5]=3 [42]=3 [4]=3 [41]=3 [0]=3 [40]=3 [25]=3 [39]=3 [24]=3)"
    literal_transitions[0]="([2]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="64 76 36 75 35 74 23 73 34 72 22 71 33 21 70 32 69 31 68 20 63 30 62 19 61 29 60 18 59 17 58 16 57 15 56 14 55 28 13 54 27 53 3 52 26 51 12 37 50 11 49 10 48 9 47 8 46 7 45 1 44 6 43 5 42 4 41 0 40 25 39 24" [4]="67 66 65" [3]="38" [2]="76 36 75 35 74 23 73 34 72 22 71 33 21 70 32 69 31 68 20 63 30 62 19 61 29 60 18 59 17 58 16 57 15 56 14 55 28 13 54 27 53 3 52 26 51 12 37 50 11 49 10 48 9 47 8 46 7 45 1 44 6 43 5 42 4 41 0 40 25 39 24" [0]="2")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_42 () {
    local -a literals=("--thread-spec=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_43 () {
    local -a literals=("YYYY-MM-DD" "MM/DD/YY" "minutes" "seconds" "--time=" "THH:MM" "MMDDYY" "HH:MM" "weeks" "hours" "days" ":SS" "now" "+1")
    local -A literal_transitions=()
    literal_transitions[1]="([12]=2 [7]=3 [6]=4 [1]=4 [0]=5)"
    literal_transitions[5]="([5]=3)"
    literal_transitions[3]="([11]=4)"
    literal_transitions[2]="([13]=6)"
    literal_transitions[0]="([4]=1)"
    literal_transitions[6]="([3]=4 [2]=4 [9]=4 [10]=4 [8]=4)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="12 7 6 1 0" [5]="5" [3]="11" [2]="13" [0]="4" [6]="3 2 9 10 8")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_44 () {
    local -a literals=("--time-min=" "YYYY-MM-DD" "MM/DD/YY" "minutes" "seconds" "THH:MM" "MMDDYY" "HH:MM" "weeks" "hours" "days" ":SS" "now" "+1")
    local -A literal_transitions=()
    literal_transitions[1]="([12]=2 [7]=3 [6]=4 [2]=4 [1]=5)"
    literal_transitions[5]="([5]=3)"
    literal_transitions[3]="([11]=4)"
    literal_transitions[2]="([13]=6)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[6]="([4]=4 [3]=4 [9]=4 [10]=4 [8]=4)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="12 7 6 2 1" [5]="5" [3]="11" [2]="13" [0]="0" [6]="4 3 9 10 8")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_45 () {
    local -a literals=("--tres-bind=" "...")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_46 () {
    local -a literals=("--tres-per-task=" "...")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_47 () {
    local -a literals=("--uid=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_48 () {
    local -a literals=("--wckey=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([10]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="10")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_49 () {
    local -a literals=("--wrap=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([11]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="11")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_50 () {
    local -a literals=("--cluster-constraint=" "!")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([12]=3)"
    command_transitions[2]="([12]=3)"
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=([1]="12" [2]="12")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_51 () {
    local -a literals=(".." ",")
    local -A literal_transitions=()
    literal_transitions[0]="([1]=1 [0]=2)"
    literal_transitions[3]="([0]=2)"
    local -A command_transitions=()
    command_transitions[1]="([12]=3)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="1 0" [3]="0")
    local -A commands_level_0=([1]="12")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_52 () {
    local -a literals=(",")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([12]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="12")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_53 () {
    local -a literals=("--constraint=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([12]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="12")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_54 () {
    local -a literals=(",")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([12]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=()
    local -A literal_transitions_level_2=([0]="0")
    local -A commands_level_0=([1]="12")
    local -A commands_level_1=()
    local -A commands_level_2=()
    local max_fallback_level=2
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_55 () {
    local -a literals=("--nodefile=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([1]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="1")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_56 () {
    local -a literals=("--mem=" "T" "G" "M" "K" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([14]=2 [13]=3 [12]=3 [11]=3 [10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3)"
    literal_transitions[3]="([14]=3 [13]=3 [12]=3 [11]=3 [10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=4 [3]=4 [2]=4 [1]=4)"
    literal_transitions[2]="([4]=4 [3]=4 [2]=4 [1]=4)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="14 13 12 11 10 9 8 7 6 5" [3]="14 13 12 11 10 9 8 7 6 5 4 3 2 1" [2]="4 3 2 1" [0]="0")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_57 () {
    local -a literals=("--mincpus=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_58 () {
    local -a literals=("--reservation=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([13]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="13")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_59 () {
    local -a literals=("--tmp=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_60 () {
    local -a literals=("--nodelist=" ",")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[4]="([1]=3)"
    local -A command_transitions=()
    command_transitions[1]="([14]=2 [1]=2)"
    command_transitions[3]="([14]=4)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="1" [0]="0" [4]="1")
    local -A commands_level_0=([1]="14 1" [3]="14")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_61 () {
    local -a literals=("--exclude=" ",")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[4]="([1]=3)"
    local -A command_transitions=()
    command_transitions[1]="([14]=2 [1]=2)"
    command_transitions[3]="([14]=4)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="1" [0]="0" [4]="1")
    local -A commands_level_0=([1]="14 1" [3]="14")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_62 () {
    local -a literals=("--exclusive" "=user")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="1" [0]="0")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_63 () {
    local -a literals=("--exclusive" "=mcs")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="1" [0]="0")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_64 () {
    local -a literals=("--mem-per-cpu=" "T" "G" "M" "K" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([14]=2 [13]=3 [12]=3 [11]=3 [10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3)"
    literal_transitions[3]="([14]=3 [13]=3 [12]=3 [11]=3 [10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=4 [3]=4 [2]=4 [1]=4)"
    literal_transitions[2]="([4]=4 [3]=4 [2]=4 [1]=4)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="14 13 12 11 10 9 8 7 6 5" [3]="14 13 12 11 10 9 8 7 6 5 4 3 2 1" [2]="4 3 2 1" [0]="0")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_65 () {
    local -a literals=("--sockets-per-node=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_66 () {
    local -a literals=("--cores-per-socket=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_67 () {
    local -a literals=("--threads-per-core=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_68 () {
    local -a literals=("--extra-node-info=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_69 () {
    local -a literals=("--ntasks-per-core=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_70 () {
    local -a literals=("--ntasks-per-socket=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_71 () {
    local -a literals=("--cpus-per-gpu=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_72 () {
    local -a literals=("--gpus=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_73 () {
    local -a literals=("--gpu-bind=" "...")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="1" [0]="0")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_74 () {
    local -a literals=("--gpu-freq=" "...")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="1" [0]="0")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_75 () {
    local -a literals=("--gpus-per-node=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_76 () {
    local -a literals=("--gpus-per-socket=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_77 () {
    local -a literals=("--gpus-per-task=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_78 () {
    local -a literals=("--mem-per-gpu=" "9" "8" "7" "6" "5" "4" "3" "2" "1" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[3]="([10]=3 [9]=3 [8]=3 [7]=3 [6]=3 [5]=3 [4]=3 [3]=3 [2]=3 [1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="10 9 8 7 6 5 4 3 2 1" [0]="0" [3]="10 9 8 7 6 5 4 3 2 1")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_79 () {
    local -a literals=("9" "8" "7" "6" "5" "4" "3" "2" "0" "1")
    local -A literal_transitions=()
    literal_transitions[1]="([9]=1 [8]=1 [7]=1 [6]=1 [5]=1 [4]=1 [3]=1 [2]=1 [1]=1 [0]=1)"
    literal_transitions[0]="([9]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="9 8 7 6 5 4 3 2 1 0" [0]="9")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_80 () {
    local -a literals=("9" "8" "7" "6" "5" "4" "3" "1" "0" "2")
    local -A literal_transitions=()
    literal_transitions[1]="([9]=1 [8]=1 [7]=1 [6]=1 [5]=1 [4]=1 [3]=1 [2]=1 [1]=1 [0]=1)"
    literal_transitions[0]="([9]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="9 8 7 6 5 4 3 2 1 0" [0]="9")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_81 () {
    local -a literals=("9" "8" "7" "6" "5" "4" "2" "1" "0" "3")
    local -A literal_transitions=()
    literal_transitions[1]="([9]=1 [8]=1 [7]=1 [6]=1 [5]=1 [4]=1 [3]=1 [2]=1 [1]=1 [0]=1)"
    literal_transitions[0]="([9]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="9 8 7 6 5 4 3 2 1 0" [0]="9")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_82 () {
    local -a literals=("9" "8" "7" "6" "5" "3" "2" "1" "0" "4")
    local -A literal_transitions=()
    literal_transitions[1]="([9]=1 [8]=1 [7]=1 [6]=1 [5]=1 [4]=1 [3]=1 [2]=1 [1]=1 [0]=1)"
    literal_transitions[0]="([9]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="9 8 7 6 5 4 3 2 1 0" [0]="9")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_83 () {
    local -a literals=("9" "8" "7" "6" "4" "3" "2" "1" "0" "5")
    local -A literal_transitions=()
    literal_transitions[1]="([9]=1 [8]=1 [7]=1 [6]=1 [5]=1 [4]=1 [3]=1 [2]=1 [1]=1 [0]=1)"
    literal_transitions[0]="([9]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="9 8 7 6 5 4 3 2 1 0" [0]="9")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_84 () {
    local -a literals=("9" "8" "7" "5" "4" "3" "2" "1" "0" "6")
    local -A literal_transitions=()
    literal_transitions[1]="([9]=1 [8]=1 [7]=1 [6]=1 [5]=1 [4]=1 [3]=1 [2]=1 [1]=1 [0]=1)"
    literal_transitions[0]="([9]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="9 8 7 6 5 4 3 2 1 0" [0]="9")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_85 () {
    local -a literals=("9" "8" "6" "5" "4" "3" "2" "1" "0" "7")
    local -A literal_transitions=()
    literal_transitions[1]="([9]=1 [8]=1 [7]=1 [6]=1 [5]=1 [4]=1 [3]=1 [2]=1 [1]=1 [0]=1)"
    literal_transitions[0]="([9]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="9 8 7 6 5 4 3 2 1 0" [0]="9")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_86 () {
    local -a literals=("9" "7" "6" "5" "4" "3" "2" "1" "0" "8")
    local -A literal_transitions=()
    literal_transitions[1]="([9]=1 [8]=1 [7]=1 [6]=1 [5]=1 [4]=1 [3]=1 [2]=1 [1]=1 [0]=1)"
    literal_transitions[0]="([9]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="9 8 7 6 5 4 3 2 1 0" [0]="9")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_87 () {
    local -a literals=("8" "7" "6" "5" "4" "3" "2" "1" "0" "9")
    local -A literal_transitions=()
    literal_transitions[1]="([9]=1 [8]=1 [7]=1 [6]=1 [5]=1 [4]=1 [3]=1 [2]=1 [1]=1 [0]=1)"
    literal_transitions[0]="([9]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="9 8 7 6 5 4 3 2 1 0" [0]="9")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_88 () {
    local -a literals=(",")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([14]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="14")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_89 () {
    local -a literals=(",")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([14]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="14")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_90 () {
    local -a literals=("9" "8" "7" "6" "5" "4" "3" "2" "0" "1")
    local -A literal_transitions=()
    literal_transitions[1]="([9]=1 [8]=1 [7]=1 [6]=1 [5]=1 [4]=1 [3]=1 [2]=1 [1]=1 [0]=1)"
    literal_transitions[0]="([9]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="9 8 7 6 5 4 3 2 1 0" [0]="9")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_91 () {
    local -a literals=("9" "8" "7" "6" "5" "4" "3" "1" "0" "2")
    local -A literal_transitions=()
    literal_transitions[1]="([9]=1 [8]=1 [7]=1 [6]=1 [5]=1 [4]=1 [3]=1 [2]=1 [1]=1 [0]=1)"
    literal_transitions[0]="([9]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="9 8 7 6 5 4 3 2 1 0" [0]="9")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_92 () {
    local -a literals=("9" "8" "7" "6" "5" "4" "2" "1" "0" "3")
    local -A literal_transitions=()
    literal_transitions[1]="([9]=1 [8]=1 [7]=1 [6]=1 [5]=1 [4]=1 [3]=1 [2]=1 [1]=1 [0]=1)"
    literal_transitions[0]="([9]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="9 8 7 6 5 4 3 2 1 0" [0]="9")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_93 () {
    local -a literals=("9" "8" "7" "6" "5" "3" "2" "1" "0" "4")
    local -A literal_transitions=()
    literal_transitions[1]="([9]=1 [8]=1 [7]=1 [6]=1 [5]=1 [4]=1 [3]=1 [2]=1 [1]=1 [0]=1)"
    literal_transitions[0]="([9]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="9 8 7 6 5 4 3 2 1 0" [0]="9")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_94 () {
    local -a literals=("9" "8" "7" "6" "4" "3" "2" "1" "0" "5")
    local -A literal_transitions=()
    literal_transitions[1]="([9]=1 [8]=1 [7]=1 [6]=1 [5]=1 [4]=1 [3]=1 [2]=1 [1]=1 [0]=1)"
    literal_transitions[0]="([9]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="9 8 7 6 5 4 3 2 1 0" [0]="9")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_95 () {
    local -a literals=("9" "8" "7" "5" "4" "3" "2" "1" "0" "6")
    local -A literal_transitions=()
    literal_transitions[1]="([9]=1 [8]=1 [7]=1 [6]=1 [5]=1 [4]=1 [3]=1 [2]=1 [1]=1 [0]=1)"
    literal_transitions[0]="([9]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="9 8 7 6 5 4 3 2 1 0" [0]="9")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_96 () {
    local -a literals=("9" "8" "6" "5" "4" "3" "2" "1" "0" "7")
    local -A literal_transitions=()
    literal_transitions[1]="([9]=1 [8]=1 [7]=1 [6]=1 [5]=1 [4]=1 [3]=1 [2]=1 [1]=1 [0]=1)"
    literal_transitions[0]="([9]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="9 8 7 6 5 4 3 2 1 0" [0]="9")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_97 () {
    local -a literals=("9" "7" "6" "5" "4" "3" "2" "1" "0" "8")
    local -A literal_transitions=()
    literal_transitions[1]="([9]=1 [8]=1 [7]=1 [6]=1 [5]=1 [4]=1 [3]=1 [2]=1 [1]=1 [0]=1)"
    literal_transitions[0]="([9]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="9 8 7 6 5 4 3 2 1 0" [0]="9")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_98 () {
    local -a literals=("8" "7" "6" "5" "4" "3" "2" "1" "0" "9")
    local -A literal_transitions=()
    literal_transitions[1]="([9]=1 [8]=1 [7]=1 [6]=1 [5]=1 [4]=1 [3]=1 [2]=1 [1]=1 [0]=1)"
    literal_transitions[0]="([9]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="9 8 7 6 5 4 3 2 1 0" [0]="9")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword () {
    [[ $# -ne 2 ]] && return 1
    local mode=$1
    local word=$2

    local char_index=0
    local matched=0
    local nliterals=${#literals[@]}
    while true; do
        if [[ $char_index -ge ${#word} ]]; then
            matched=1
            break
        fi

        local subword=${word:$char_index}

        if [[ -v "literal_transitions[$state]" ]]; then
            local -A state_transitions=${literal_transitions[$state]}

            for ((literal_id = 0; literal_id < nliterals; literal_id++)); do
                local literal=${literals[$literal_id]}
                if [[ $subword == $literal && -v "state_transitions[$literal_id]" ]]; then
                    state=${state_transitions[$literal_id]}
                    char_index=$((char_index + ${#literal}))
                    continue 2
                fi
                if [[ $literal == $subword* ]]; then
                    break 2
                fi
                if [[ $subword == $literal* && -v "state_transitions[$literal_id]" ]]; then
                    state=${state_transitions[$literal_id]}
                    char_index=$((char_index + ${#literal}))
                    continue 2
                fi
            done
        fi

        if [[ -v "command_transitions[$state]" ]]; then
            local matched_prefix="${word:0:$char_index}"
            local -A state_commands=${command_transitions[$state]}
            for cmd_id in "${!state_commands[@]}"; do
                readarray -t subword_candidates < <(_sbatch_cmd_$cmd_id "$subword" "$matched_prefix" | while read -r f1 _; do echo "$f1"; done)
                if [[ ${#subword_candidates[@]} -gt 0 ]]; then
                    indexes=($(
                        for i in "${!subword_candidates[@]}"; do
                            printf '%s %s %s\n' $i "${#subword_candidates[i]}" "${subword_candidates[i]}"
                        done | sort -nrk2,2 -rk3 | cut -f1 -d' '
                    ))
                    decreasing_length=()
                    for i in "${indexes[@]}" ; do
                        decreasing_length+=("${subword_candidates[i]}")
                    done

                    for candidate in "${decreasing_length[@]}"; do
                        if [[ $candidate == $subword ]]; then
                            match_len=${#candidate}
                            char_index=$((char_index + match_len))
                            state=${state_commands[$cmd_id]}
                            continue 3
                        fi

                        if [[ $candidate == $subword* ]]; then
                            break 3
                        fi

                        if [[ $subword == $candidate* ]]; then
                            match_len=${#candidate}
                            char_index=$((char_index + match_len))
                            state=${state_commands[$cmd_id]}
                            continue 3
                        fi
                    done
                fi
            done
        fi

        break
    done

    if [[ $mode = matches ]]; then
        return $((1 - matched))
    fi

    local matched_prefix="${word:0:$char_index}"
    local completed_prefix="${word:$char_index}"

    local -a subword_candidates=()
    local -a subword_matches=()
    for (( subword_fallback_level=0; subword_fallback_level <= max_fallback_level; subword_fallback_level++ )) {
        eval "local literal_transitions_name=literal_transitions_level_${subword_fallback_level}"
        eval "local -a transitions=(\${$literal_transitions_name[$state]})"
        for literal_id in "${transitions[@]}"; do
            local literal=${literals[$literal_id]}
            subword_candidates+=("$matched_prefix$literal")
        done
        __complgen_match "$matched_prefix$completed_prefix" subword_candidates subword_matches

        eval "local commands_name=commands_level_${subword_fallback_level}"
        eval "local -a transitions=(\${$commands_name[$state]})"
        for command_id in "${transitions[@]}"; do
            readarray -t subword_candidates < <(_sbatch_cmd_$command_id "$completed_prefix" "$matched_prefix" | while read -r f1 _; do echo "$f1"; done)
            local -a filtered_candidates=()
            __complgen_match "$completed_prefix" subword_candidates filtered_candidates
            for item in "${filtered_candidates[@]}"; do
                subword_matches+=("$matched_prefix$item")
            done
        done

        if [[ ${#subword_matches[@]} -gt 0 ]]; then
            matches+=("${subword_matches[@]}")
            break
        fi
    }
    return 0
}

_sbatch () {
    if [[ $(type -t _get_comp_words_by_ref) != function ]]; then
        echo _get_comp_words_by_ref: function not defined.  Make sure the bash-completion system package is installed
        return 1
    fi

    local words cword
    _get_comp_words_by_ref -n "$COMP_WORDBREAKS" words cword

    local -a literals=("--use-min-nodes" "--oversubscribe" "--get-user-env" "--contiguous" "--spread-job" "--overcommit" "--no-requeue" "--ignore-pbs" "--parsable" "--version" "--verbose" "--requeue" "--no-kill" "--reboot" "--usage" "--quiet" "--help" "--wait" "--hold" "--" "-V" "-h" "-G" "-B" "-x" "-w" "-F" "-C" "-W" "-v" "-t" "-S" "-s" "-Q" "-q" "-p" "-O" "-o" "-N" "-n" "-m" "-M" "-L" "-k" "-J" "-i" "-H" "-e" "-D" "-d" "-c" "-b" "-A" "-a" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([54]=0)"
    literal_transitions[0]="([53]=0 [52]=0 [51]=0 [50]=0 [49]=0 [48]=0 [47]=0 [2]=0 [46]=0 [18]=0 [7]=0 [45]=0 [44]=0 [43]=0 [12]=0 [42]=0 [41]=0 [40]=0 [39]=0 [6]=0 [38]=1 [37]=0 [36]=0 [5]=0 [35]=0 [8]=0 [34]=0 [33]=0 [15]=0 [13]=0 [11]=0 [32]=0 [1]=0 [31]=0 [4]=0 [30]=0 [0]=0 [29]=0 [10]=0 [28]=0 [17]=0 [3]=0 [27]=2 [26]=0 [25]=3 [24]=4 [23]=5 [22]=5 [21]=0 [16]=0 [14]=0 [20]=0 [9]=0)"
    literal_transitions[7]="([53]=0 [52]=0 [51]=0 [50]=0 [49]=0 [48]=0 [47]=0 [2]=0 [46]=0 [18]=0 [7]=0 [45]=0 [44]=0 [43]=0 [12]=0 [42]=0 [41]=0 [40]=0 [39]=0 [6]=0 [38]=1 [37]=0 [36]=0 [5]=0 [35]=0 [8]=0 [34]=0 [33]=0 [15]=0 [13]=0 [11]=0 [32]=0 [1]=0 [31]=0 [4]=0 [30]=0 [0]=0 [29]=0 [10]=0 [28]=0 [17]=0 [3]=0 [27]=2 [26]=0 [25]=3 [24]=4 [23]=5 [22]=5 [21]=0 [16]=0 [14]=0 [20]=0 [9]=0)"
    literal_transitions[6]="([19]=6)"
    literal_transitions[5]="([54]=0)"
    literal_transitions[4]="([53]=0 [52]=0 [51]=0 [50]=0 [49]=0 [48]=0 [47]=0 [2]=0 [46]=0 [18]=0 [7]=0 [45]=0 [44]=0 [43]=0 [12]=0 [42]=0 [41]=0 [40]=0 [39]=0 [6]=0 [38]=1 [37]=0 [36]=0 [5]=0 [35]=0 [8]=0 [34]=0 [33]=0 [15]=0 [13]=0 [11]=0 [32]=0 [1]=0 [31]=0 [4]=0 [30]=0 [0]=0 [29]=0 [10]=0 [28]=0 [17]=0 [3]=0 [27]=2 [26]=0 [25]=3 [24]=4 [23]=5 [22]=5 [21]=0 [16]=0 [14]=0 [20]=0 [9]=0)"
    literal_transitions[3]="([53]=0 [52]=0 [51]=0 [50]=0 [49]=0 [48]=0 [47]=0 [2]=0 [46]=0 [18]=0 [7]=0 [45]=0 [44]=0 [43]=0 [12]=0 [42]=0 [41]=0 [40]=0 [39]=0 [6]=0 [38]=1 [37]=0 [36]=0 [5]=0 [35]=0 [8]=0 [34]=0 [33]=0 [15]=0 [13]=0 [11]=0 [32]=0 [1]=0 [31]=0 [4]=0 [30]=0 [0]=0 [29]=0 [10]=0 [28]=0 [17]=0 [3]=0 [27]=2 [26]=0 [25]=3 [24]=4 [23]=5 [22]=5 [21]=0 [16]=0 [14]=0 [20]=0 [9]=0)"
    literal_transitions[8]="([53]=0 [52]=0 [51]=0 [50]=0 [49]=0 [48]=0 [47]=0 [2]=0 [46]=0 [18]=0 [7]=0 [45]=0 [44]=0 [43]=0 [12]=0 [42]=0 [41]=0 [40]=0 [39]=0 [6]=0 [38]=1 [37]=0 [36]=0 [5]=0 [35]=0 [8]=0 [34]=0 [33]=0 [15]=0 [13]=0 [11]=0 [32]=0 [1]=0 [31]=0 [4]=0 [30]=0 [0]=0 [29]=0 [10]=0 [28]=0 [17]=0 [3]=0 [27]=2 [26]=0 [25]=3 [24]=4 [23]=5 [22]=5 [21]=0 [16]=0 [14]=0 [20]=0 [9]=0)"
    local -A command_transitions=()
    command_transitions[8]="([15]=6)"
    command_transitions[4]="([14]=0 [1]=0 [15]=6)"
    command_transitions[3]="([14]=0 [1]=0 [15]=6)"
    command_transitions[2]="([12]=0)"
    command_transitions[0]="([15]=6)"
    command_transitions[7]="([15]=6)"
    command_transitions[6]="([1]=6 [11]=6)"
    local -A subword_transitions
    subword_transitions[0]="([0]=0 [1]=0 [2]=0 [3]=0 [4]=0 [5]=0 [6]=0 [7]=0 [8]=0 [9]=0 [10]=0 [11]=0 [12]=0 [13]=0 [14]=0 [15]=0 [16]=0 [17]=0 [18]=0 [19]=0 [20]=0 [21]=0 [22]=0 [23]=0 [24]=0 [25]=0 [26]=0 [27]=0 [28]=0 [29]=0 [30]=0 [31]=0 [32]=0 [33]=0 [34]=0 [35]=0 [36]=0 [37]=0 [38]=0 [39]=0 [40]=0 [41]=0 [42]=0 [43]=0 [44]=0 [45]=0 [46]=0 [47]=0 [48]=0 [49]=0 [50]=0 [51]=0 [52]=0 [53]=0 [54]=0 [55]=0 [56]=0 [57]=0 [58]=0 [59]=0 [60]=0 [61]=0 [62]=0 [63]=0 [64]=0 [65]=0 [66]=0 [67]=0 [68]=0 [69]=0 [70]=0 [71]=0 [72]=0 [73]=0 [74]=0 [75]=0 [76]=0 [77]=0 [78]=0)"
    subword_transitions[1]="([79]=0 [80]=0 [81]=0 [82]=0 [83]=0 [84]=0 [85]=0 [86]=0 [87]=0)"
    subword_transitions[3]="([0]=0 [1]=0 [2]=0 [3]=0 [4]=0 [5]=0 [6]=0 [7]=0 [8]=0 [9]=0 [10]=0 [11]=0 [12]=0 [13]=0 [14]=0 [15]=0 [16]=0 [17]=0 [18]=0 [19]=0 [20]=0 [21]=0 [22]=0 [23]=0 [24]=0 [25]=0 [26]=0 [27]=0 [28]=0 [29]=0 [30]=0 [31]=0 [32]=0 [33]=0 [34]=0 [35]=0 [36]=0 [37]=0 [38]=0 [39]=0 [40]=0 [41]=0 [42]=0 [43]=0 [44]=0 [45]=0 [46]=0 [47]=0 [48]=0 [49]=0 [50]=0 [51]=0 [52]=0 [53]=0 [54]=0 [55]=0 [56]=0 [57]=0 [58]=0 [59]=0 [88]=7 [60]=0 [61]=0 [62]=0 [63]=0 [64]=0 [65]=0 [66]=0 [67]=0 [68]=0 [69]=0 [70]=0 [71]=0 [72]=0 [73]=0 [74]=0 [75]=0 [76]=0 [77]=0 [78]=0)"
    subword_transitions[4]="([0]=0 [1]=0 [2]=0 [3]=0 [4]=0 [5]=0 [6]=0 [7]=0 [8]=0 [9]=0 [10]=0 [11]=0 [12]=0 [13]=0 [14]=0 [15]=0 [16]=0 [17]=0 [18]=0 [19]=0 [20]=0 [21]=0 [22]=0 [23]=0 [24]=0 [25]=0 [26]=0 [27]=0 [28]=0 [29]=0 [30]=0 [31]=0 [32]=0 [33]=0 [34]=0 [35]=0 [36]=0 [37]=0 [38]=0 [39]=0 [40]=0 [41]=0 [42]=0 [43]=0 [44]=0 [45]=0 [46]=0 [47]=0 [48]=0 [49]=0 [50]=0 [51]=0 [52]=0 [53]=0 [54]=0 [55]=0 [56]=0 [57]=0 [58]=0 [59]=0 [60]=0 [89]=8 [61]=0 [62]=0 [63]=0 [64]=0 [65]=0 [66]=0 [67]=0 [68]=0 [69]=0 [70]=0 [71]=0 [72]=0 [73]=0 [74]=0 [75]=0 [76]=0 [77]=0 [78]=0)"
    subword_transitions[5]="([90]=0 [91]=0 [92]=0 [93]=0 [94]=0 [95]=0 [96]=0 [97]=0 [98]=0)"
    subword_transitions[7]="([0]=0 [1]=0 [2]=0 [3]=0 [4]=0 [5]=0 [6]=0 [7]=0 [8]=0 [9]=0 [10]=0 [11]=0 [12]=0 [13]=0 [14]=0 [15]=0 [16]=0 [17]=0 [18]=0 [19]=0 [20]=0 [21]=0 [22]=0 [23]=0 [24]=0 [25]=0 [26]=0 [27]=0 [28]=0 [29]=0 [30]=0 [31]=0 [32]=0 [33]=0 [34]=0 [35]=0 [36]=0 [37]=0 [38]=0 [39]=0 [40]=0 [41]=0 [42]=0 [43]=0 [44]=0 [45]=0 [46]=0 [47]=0 [48]=0 [49]=0 [50]=0 [51]=0 [52]=0 [53]=0 [54]=0 [55]=0 [56]=0 [57]=0 [58]=0 [59]=0 [88]=7 [60]=0 [61]=0 [62]=0 [63]=0 [64]=0 [65]=0 [66]=0 [67]=0 [68]=0 [69]=0 [70]=0 [71]=0 [72]=0 [73]=0 [74]=0 [75]=0 [76]=0 [77]=0 [78]=0)"
    subword_transitions[8]="([0]=0 [1]=0 [2]=0 [3]=0 [4]=0 [5]=0 [6]=0 [7]=0 [8]=0 [9]=0 [10]=0 [11]=0 [12]=0 [13]=0 [14]=0 [15]=0 [16]=0 [17]=0 [18]=0 [19]=0 [20]=0 [21]=0 [22]=0 [23]=0 [24]=0 [25]=0 [26]=0 [27]=0 [28]=0 [29]=0 [30]=0 [31]=0 [32]=0 [33]=0 [34]=0 [35]=0 [36]=0 [37]=0 [38]=0 [39]=0 [40]=0 [41]=0 [42]=0 [43]=0 [44]=0 [45]=0 [46]=0 [47]=0 [48]=0 [49]=0 [50]=0 [51]=0 [52]=0 [53]=0 [54]=0 [55]=0 [56]=0 [57]=0 [58]=0 [59]=0 [60]=0 [89]=8 [61]=0 [62]=0 [63]=0 [64]=0 [65]=0 [66]=0 [67]=0 [68]=0 [69]=0 [70]=0 [71]=0 [72]=0 [73]=0 [74]=0 [75]=0 [76]=0 [77]=0 [78]=0)"

    local state=0
    local word_index=1
    local nliterals=${#literals[@]}
    while [[ $word_index -lt $cword ]]; do
        local word=${words[$word_index]}

        if [[ -v "literal_transitions[$state]" ]]; then
            local -A state_transitions=${literal_transitions[$state]}

            for ((literal_id = 0; literal_id < nliterals; literal_id++)); do
                if [[ ${literals[$literal_id]} = "$word" ]]; then
                    if [[ -v "state_transitions[$literal_id]" ]]; then
                        state=${state_transitions[$literal_id]}
                        word_index=$((word_index + 1))
                        continue 2
                    fi
                fi
            done
        fi

        if [[ -v "subword_transitions[$state]" ]]; then
            local -A state_transitions=${subword_transitions[$state]}

            for subword_id in "${!state_transitions[@]}"; do
                if _sbatch_subword_"${subword_id}" matches "$word"; then
                    state=${state_transitions[$subword_id]}
                    word_index=$((word_index + 1))
                    continue 2
                fi
            done
        fi

        if [[ -v "command_transitions[$state]" ]]; then
            local -A state_commands=${command_transitions[$state]}
            for cmd_id in "${!state_commands[@]}"; do
                readarray -t candidates < <(_sbatch_cmd_$cmd_id "" "" | while read -r f1 _; do echo "$f1"; done)
                if [[ ${#candidates[@]} -gt 0 ]]; then
                    indexes=($(
                        for i in "${!candidates[@]}" ; do
                            printf '%s %s %s\n' $i "${#candidates[i]}" "${candidates[i]}"
                        done | sort -nrk2,2 -rk3 | cut -f1 -d' '
                    ))
                    decreasing_length=()
                    for i in "${indexes[@]}"; do
                        decreasing_length+=("${candidates[i]}")
                    done

                    for candidate in "${decreasing_length[@]}"; do
                        if [[ $candidate == $word ]]; then
                            state=${state_commands[$cmd_id]}
                            word_index=$((word_index + 1))
                            continue 3
                        fi
                    done

                    if [[ $(($word_index + 1)) == $cword ]]; then
                        break 3
                    fi
                fi
            done
        fi

        return 1
    done

    local -A literal_transitions_level_0=([1]="54" [4]="53 52 51 50 49 48 47 2 46 18 7 45 44 43 12 42 41 40 39 6 38 37 36 5 35 8 34 33 15 13 11 32 1 31 4 30 0 29 10 28 17 27" [3]="53 52 51 50 49 48 47 2 46 18 7 45 44 43 12 42 41 40 39 6 38 37 36 5 35 8 34 33 15 13 11 32 1 31 4 30 0 29 10 28 17 27" [0]="53 52 51 50 49 48 47 2 46 18 7 45 44 43 12 42 41 40 39 6 38 37 36 5 35 8 34 33 15 13 11 32 1 31 4 30 0 29 10 28 17 27" [7]="53 52 51 50 49 48 47 2 46 18 7 45 44 43 12 42 41 40 39 6 38 37 36 5 35 8 34 33 15 13 11 32 1 31 4 30 0 29 10 28 17 27" [8]="53 52 51 50 49 48 47 2 46 18 7 45 44 43 12 42 41 40 39 6 38 37 36 5 35 8 34 33 15 13 11 32 1 31 4 30 0 29 10 28 17 27")
    local -A literal_transitions_level_1=([5]="54" [4]="3 26 25 24 23 22 21 16 14 20 9" [3]="3 26 25 24 23 22 21 16 14 20 9" [0]="3 26 25 24 23 22 21 16 14 20 9" [7]="3 26 25 24 23 22 21 16 14 20 9" [8]="3 26 25 24 23 22 21 16 14 20 9")
    local -A literal_transitions_level_2=([6]="19")
    local -A commands_level_0=([6]="1 11" [4]="14 1 15" [3]="14 1 15" [2]="12" [0]="15" [7]="15" [8]="15")
    local -A commands_level_1=()
    local -A commands_level_2=()
    local -A subword_transitions_level_0=([1]="79 80 81 82 83 84 85 86 87" [4]="0 1 2 3 4 5 6 7 8 10 11 12 13 14 15 16 17 18 19 20 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50" [3]="0 1 2 3 4 5 6 7 8 10 11 12 13 14 15 16 17 18 19 20 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50" [0]="0 1 2 3 4 5 6 7 8 10 11 12 13 14 15 16 17 18 19 20 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50" [7]="0 1 2 3 4 5 6 7 8 10 11 12 13 14 15 16 17 18 19 20 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50" [8]="0 1 2 3 4 5 6 7 8 10 11 12 13 14 15 16 17 18 19 20 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50")
    local -A subword_transitions_level_1=([5]="90 91 92 93 94 95 96 97 98" [4]="9 21 51 52 53 55 56 57 58 59 60 89 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78" [3]="9 21 51 52 53 55 56 57 58 59 88 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78" [0]="9 21 51 52 53 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78" [7]="9 21 51 52 53 55 56 57 58 59 88 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78" [8]="9 21 51 52 53 55 56 57 58 59 60 89 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78")
    local -A subword_transitions_level_2=([4]="54" [3]="54" [0]="54" [7]="54" [8]="54")

    local ignore_case=$(bind -v | while read -r _ var value; do [[ $var = completion-ignore-case ]] && echo $value; done)
    if [[ $ignore_case = on ]]; then
        __complgen_match () {
            [[ $# -lt 3 ]] && return 1
            local prefix=$1
            declare -n candidates_=$2
            declare -n matches_=$3
            if [[ -z $prefix ]]; then
                matches_+=("${candidates_[@]}")
            else
                prefix=${prefix,,}
                prefix=$(printf '%q' "$prefix")
                for line in "${candidates_[@]}"; do
                    [[ ${line,,} = ${prefix}* ]] && matches_+=("$line")
                done
            fi
        }
    else
        __complgen_match () {
            [[ $# -lt 3 ]] && return 1
            local prefix=$1
            declare -n candidates_=$2
            declare -n matches_=$3
            if [[ -z $prefix ]]; then
                matches_+=("${candidates_[@]}")
            else
                prefix=$(printf '%q' "$prefix")
                for line in "${candidates_[@]}"; do
                    [[ $line = ${prefix}* ]] && matches_+=("$line")
                done
            fi
        }
    fi


    local -a candidates=()
    local -a matches=()
    local max_fallback_level=2
    local prefix="${words[$cword]}"
    for (( fallback_level=0; fallback_level <= max_fallback_level; fallback_level++ )) {
        eval "local literal_transitions_name=literal_transitions_level_${fallback_level}"
        eval "local -a transitions=(\${$literal_transitions_name[$state]})"
        for literal_id in "${transitions[@]}"; do
            local literal="${literals[$literal_id]}"
            candidates+=("$literal ")
        done
        if [[ ${#candidates[@]} -gt 0 ]]; then
            __complgen_match "$prefix" candidates matches
        fi
        eval "local subword_transitions_name=subword_transitions_level_${fallback_level}"
        eval "local -a transitions=(\${$subword_transitions_name[$state]})"
        for subword_id in "${transitions[@]}"; do
            _sbatch_subword_$subword_id complete "$prefix"
        done
        eval "local commands_name=commands_level_${fallback_level}"
        eval "local -a transitions=(\${$commands_name[$state]})"
        for command_id in "${transitions[@]}"; do
            readarray -t candidates < <(_sbatch_cmd_$command_id "$prefix" "" | while read -r f1 _; do echo "$f1"; done)
            if [[ ${#candidates[@]} -gt 0 ]]; then
                __complgen_match "$prefix" candidates matches
            fi
        done
        if [[ ${#matches[@]} -gt 0 ]]; then
            local shortest_suffix="$prefix"
            for ((i=0; i < ${#COMP_WORDBREAKS}; i++)); do
                local char="${COMP_WORDBREAKS:$i:1}"
                local candidate=${prefix##*$char}
                if [[ ${#candidate} -lt ${#shortest_suffix} ]]; then
                    shortest_suffix=$candidate
                fi
            done
            local superfluous_prefix=""
            if [[ "$shortest_suffix" != "$prefix" ]]; then
                local superfluous_prefix=${prefix%$shortest_suffix}
            fi
            COMPREPLY=("${matches[@]#$superfluous_prefix}")
            break
        fi
    }

    return 0
}

complete -o nospace -F _sbatch sbatch
