# sbatch completion script generated by https://github.com/adaszko/complgen

if [[ ${BASH_VERSINFO[0]} -lt 4 ]]; then
    echo "This completion script requires bash 4.0 or newer (current is $BASH_VERSION)"
    exit 1
fi

_sbatch_cmd_0 () {
    sacctmgr show account -nP format=account
}

_sbatch_cmd_1 () {
    compgen -A file -- "$1"
}

_sbatch_cmd_2 () {
    squeue -u $USER -ho '%A'
}

_sbatch_cmd_3 () {
    compgen -A directory -- "$1"
}

_sbatch_cmd_4 () {
    sinfo -ho "%G" | sed 's/([^)]*)//g' | tr ':' '\n' | grep -v '^[0-9]' | sort -u
}

_sbatch_cmd_5 () {
    scontrol show lic
}

_sbatch_cmd_6 () {
    sacctmgr show cluster -nP format=clusters
}

_sbatch_cmd_7 () {
    sacctmgr show user -nP format=user
}

_sbatch_cmd_8 () {
    sinfo -ho %P
}

_sbatch_cmd_9 () {
    sacctmgr show qos -nP format=name
}

_sbatch_cmd_10 () {
    compgen -c
}

_sbatch_cmd_11 () {
    sinfo -ho %f
}

_sbatch_cmd_12 () {
    sacctmgr show reservation -nP format=name
}

_sbatch_cmd_13 () {
    sinfo -ho %n
}

_sbatch_cmd_14 () {
    compgen -f -- "$1" | grep -e '.sbatch'
}

_sbatch_subword_0 () {
    local -a literals=("--array=0" "1" ":" "%" "0" "-" ",")
    local -A literal_transitions=()
    literal_transitions[1]="([6]=2 [5]=2)"
    literal_transitions[4]="([1]=5)"
    literal_transitions[3]="([3]=4 [2]=4)"
    literal_transitions[2]="([4]=3)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="6 5" [4]="1" [3]="3 2" [2]="4" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_1 () {
    local -a literals=("--account=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([0]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="0")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_2 () {
    local -a literals=("YYYY-MM-DD" "MM/DD/YY" "--begin=" "minutes" "seconds" "THH:MM" "MMDDYY" "HH:MM" "weeks" "hours" "days" ":SS" "now" "+1")
    local -A literal_transitions=()
    literal_transitions[1]="([12]=2 [7]=3 [6]=4 [1]=4 [0]=5)"
    literal_transitions[5]="([5]=3)"
    literal_transitions[3]="([11]=4)"
    literal_transitions[2]="([13]=6)"
    literal_transitions[0]="([2]=1)"
    literal_transitions[6]="([4]=4 [3]=4 [9]=4 [10]=4 [8]=4)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="12 7 6 1 0" [5]="5" [3]="11" [2]="13" [0]="2" [6]="4 3 9 10 8")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_3 () {
    local -a literals=("--cpus-per-task=" "8")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_4 () {
    local -a literals=("--container=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([1]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="1")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_5 () {
    local -a literals=("--dependency=" "afternotok" "aftercorr" "afterany" "afterok" "after" "," ":")
    local -A literal_transitions=()
    literal_transitions[1]="([5]=2 [3]=2 [4]=2 [2]=2 [1]=2 [6]=1)"
    literal_transitions[4]="([7]=3 [6]=1)"
    literal_transitions[2]="([7]=3)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[3]="([2]=4)"
    local -A literal_transitions_level_0=([1]="5 3 4 2 1 6" [4]="7 6" [2]="7" [0]="0")
    local -A commands_level_0=([3]="2")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_6 () {
    local -a literals=("--deadline=" "YYYY-MM-DD" "MM/DD/YY" "minutes" "seconds" "THH:MM" "MMDDYY" "HH:MM" "weeks" "hours" "days" ":SS" "now" "+1")
    local -A literal_transitions=()
    literal_transitions[1]="([12]=2 [7]=3 [6]=4 [2]=4 [1]=5)"
    literal_transitions[5]="([5]=3)"
    literal_transitions[3]="([11]=4)"
    literal_transitions[2]="([13]=6)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[6]="([4]=4 [3]=4 [9]=4 [10]=4 [8]=4)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="12 7 6 2 1" [5]="5" [3]="11" [2]="13" [0]="0" [6]="4 3 9 10 8")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_7 () {
    local -a literals=("--chdir=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([3]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="3")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_8 () {
    local -a literals=("--error=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([1]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="1")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_9 () {
    local -a literals=("--export=" ",ENVVAR" "NONE" "NIL" "ALL")
    local -A literal_transitions=()
    literal_transitions[1]="([4]=2 [2]=3 [3]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[2]="([1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="4 2 3" [0]="0" [2]="1")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_10 () {
    local -a literals=("--gres=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([4]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="4")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_11 () {
    local -a literals=("--input=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([1]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="1")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_12 () {
    local -a literals=("--job-name=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([1]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="1")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_13 () {
    local -a literals=("--licenses=" ":0" ",")
    local -A literal_transitions=()
    literal_transitions[2]="([2]=3)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[4]="([2]=3 [1]=2)"
    local -A command_transitions=()
    command_transitions[1]="([5]=2)"
    command_transitions[3]="([5]=4)"
    local -A literal_transitions_level_0=([2]="2" [0]="0" [4]="2 1")
    local -A commands_level_0=([1]="5" [3]="5")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_14 () {
    local -a literals=("--clusters=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([6]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="6")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_15 () {
    local -a literals=("--distribution=" "arbitrary" "cyclic" "plane" "block")
    local -A literal_transitions=()
    literal_transitions[1]="([4]=2 [2]=2 [1]=2 [3]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="4 2 1 3" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_16 () {
    local -a literals=("TIME_LIMIT_50" "TIME_LIMIT_80" "TIME_LIMIT_90" "--mail-type=" "ARRAY_TASKS" "TIME_LIMIT" "STAGE_OUT" "REQUEUE" "BEGIN" "FAIL" "NONE" "ALL" "END")
    local -A literal_transitions=()
    literal_transitions[1]="([10]=2 [8]=2 [12]=2 [9]=2 [11]=2 [7]=2 [6]=2 [5]=2 [2]=2 [1]=2 [0]=2 [4]=2)"
    literal_transitions[0]="([3]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="10 8 12 9 11 7 6 5 2 1 0 4" [0]="3")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_17 () {
    local -a literals=("--mail-user=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([7]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="7")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_18 () {
    local -a literals=("--ntasks=" "1")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_19 () {
    local -a literals=("--nice" "=0")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_20 () {
    local -a literals=("--ntasks-per-node=" "1")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_21 () {
    local -a literals=("--nodes=" "1")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_22 () {
    local -a literals=("--output=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([1]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="1")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_23 () {
    local -a literals=("--partition=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([8]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="8")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_24 () {
    local -a literals=("--power=" "...")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_25 () {
    local -a literals=("--priority=" "0")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_26 () {
    local -a literals=("filesystem" "--profile=" "network" "energy" "task" "none" "all" ",")
    local -A literal_transitions=()
    literal_transitions[1]="([6]=2 [5]=2 [4]=2 [3]=2 [2]=2 [0]=2 [7]=3)"
    literal_transitions[4]="([7]=3)"
    literal_transitions[3]="([4]=4 [3]=4 [2]=4 [0]=4)"
    literal_transitions[0]="([1]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="6 5 4 3 2 0" [0]="1")
    local -A literal_transitions_level_1=([1]="7" [4]="7" [3]="4 3 2 0")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_27 () {
    local -a literals=("--propagate" "=rlimits")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_28 () {
    local -a literals=("--qos=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([9]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="9")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_29 () {
    local -a literals=("-requeue" "no" "--")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2 [0]=3)"
    literal_transitions[0]="([2]=1)"
    literal_transitions[2]="([0]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1 0" [0]="2" [2]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_30 () {
    local -a literals=("SIGWAITING" "SIGVTALRM" "--signal=" "SIGWINCH" "SIGXFSZ" "SIGXCPU" "SIGPROF" "SIGTTOU" "SIGTTIN" "SIGCONT" "SIGTSTP" "SIGSTOP" "SIGPOLL" "SIGCHLD" "SIGUSR2" "SIGUSR1" "SIGTERM" "SIGALRM" "SIGPIPE" "SIGSEGV" "SIGKILL" "SIGABRT" "SIGTRAP" "SIGQUIT" "SIGAIO" "SIGLWP" "SIGURG" "SIGPWR" "SIGCLD" "SIGSYS" "SIGBUS" "SIGFPE" "SIGEMT" "SIGIOT" "SIGILL" "SIGINT" "SIGHUP" "SIGIO" "60" "34" "33" "32" "31" "30" "29" "28" "27" "26" "25" "24" "23" "22" "21" "20" "19" "18" "17" "16" "15" "14" "13" "12" "11" "10" "R:" "h" "m" "s" "9" "8" "7" "6" "5" "4" "3" "2" "1")
    local -A literal_transitions=()
    literal_transitions[1]="([64]=2 [76]=3 [36]=3 [75]=3 [35]=3 [74]=3 [23]=3 [73]=3 [34]=3 [72]=3 [22]=3 [71]=3 [33]=3 [21]=3 [70]=3 [32]=3 [69]=3 [31]=3 [68]=3 [20]=3 [63]=3 [30]=3 [62]=3 [19]=3 [61]=3 [29]=3 [60]=3 [18]=3 [59]=3 [17]=3 [58]=3 [16]=3 [57]=3 [15]=3 [56]=3 [14]=3 [55]=3 [28]=3 [13]=3 [54]=3 [27]=3 [53]=3 [3]=3 [52]=3 [26]=3 [51]=3 [12]=3 [37]=3 [50]=3 [11]=3 [49]=3 [10]=3 [48]=3 [9]=3 [47]=3 [8]=3 [46]=3 [7]=3 [45]=3 [1]=3 [44]=3 [6]=3 [43]=3 [5]=3 [42]=3 [4]=3 [41]=3 [0]=3 [40]=3 [25]=3 [39]=3 [24]=3)"
    literal_transitions[4]="([67]=5 [66]=5 [65]=5)"
    literal_transitions[3]="([38]=4)"
    literal_transitions[2]="([76]=3 [36]=3 [75]=3 [35]=3 [74]=3 [23]=3 [73]=3 [34]=3 [72]=3 [22]=3 [71]=3 [33]=3 [21]=3 [70]=3 [32]=3 [69]=3 [31]=3 [68]=3 [20]=3 [63]=3 [30]=3 [62]=3 [19]=3 [61]=3 [29]=3 [60]=3 [18]=3 [59]=3 [17]=3 [58]=3 [16]=3 [57]=3 [15]=3 [56]=3 [14]=3 [55]=3 [28]=3 [13]=3 [54]=3 [27]=3 [53]=3 [3]=3 [52]=3 [26]=3 [51]=3 [12]=3 [37]=3 [50]=3 [11]=3 [49]=3 [10]=3 [48]=3 [9]=3 [47]=3 [8]=3 [46]=3 [7]=3 [45]=3 [1]=3 [44]=3 [6]=3 [43]=3 [5]=3 [42]=3 [4]=3 [41]=3 [0]=3 [40]=3 [25]=3 [39]=3 [24]=3)"
    literal_transitions[0]="([2]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="64 76 36 75 35 74 23 73 34 72 22 71 33 21 70 32 69 31 68 20 63 30 62 19 61 29 60 18 59 17 58 16 57 15 56 14 55 28 13 54 27 53 3 52 26 51 12 37 50 11 49 10 48 9 47 8 46 7 45 1 44 6 43 5 42 4 41 0 40 25 39 24" [4]="67 66 65" [3]="38" [2]="76 36 75 35 74 23 73 34 72 22 71 33 21 70 32 69 31 68 20 63 30 62 19 61 29 60 18 59 17 58 16 57 15 56 14 55 28 13 54 27 53 3 52 26 51 12 37 50 11 49 10 48 9 47 8 46 7 45 1 44 6 43 5 42 4 41 0 40 25 39 24" [0]="2")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_31 () {
    local -a literals=("YYYY-MM-DD" "MM/DD/YY" "minutes" "seconds" "--time=" "THH:MM" "MMDDYY" "HH:MM" "weeks" "hours" "days" ":SS" "now" "+1")
    local -A literal_transitions=()
    literal_transitions[1]="([12]=2 [7]=3 [6]=4 [1]=4 [0]=5)"
    literal_transitions[5]="([5]=3)"
    literal_transitions[3]="([11]=4)"
    literal_transitions[2]="([13]=6)"
    literal_transitions[0]="([4]=1)"
    literal_transitions[6]="([3]=4 [2]=4 [9]=4 [10]=4 [8]=4)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="12 7 6 1 0" [5]="5" [3]="11" [2]="13" [0]="4" [6]="3 2 9 10 8")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_32 () {
    local -a literals=("--time-min=" "YYYY-MM-DD" "MM/DD/YY" "minutes" "seconds" "THH:MM" "MMDDYY" "HH:MM" "weeks" "hours" "days" ":SS" "now" "+1")
    local -A literal_transitions=()
    literal_transitions[1]="([12]=2 [7]=3 [6]=4 [2]=4 [1]=5)"
    literal_transitions[5]="([5]=3)"
    literal_transitions[3]="([11]=4)"
    literal_transitions[2]="([13]=6)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[6]="([4]=4 [3]=4 [9]=4 [10]=4 [8]=4)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="12 7 6 2 1" [5]="5" [3]="11" [2]="13" [0]="0" [6]="4 3 9 10 8")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_33 () {
    local -a literals=("--wrap=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([10]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="10")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_34 () {
    local -a literals=("--cluster-constraint=" "!")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([11]=3)"
    command_transitions[2]="([11]=3)"
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=([1]="11" [2]="11")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_35 () {
    local -a literals=(",")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([11]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="11")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_36 () {
    local -a literals=("--constraint=" ",")
    local -A literal_transitions=()
    literal_transitions[2]="([1]=1)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([11]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([2]="1" [0]="0")
    local -A commands_level_0=([1]="11")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_37 () {
    local -a literals=("--mem=" "128G")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="1" [0]="0")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_38 () {
    local -a literals=("--mem-per-cpu=" "8G")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="1" [0]="0")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_39 () {
    local -a literals=("--mem-per-gpu=" "64G")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="1" [0]="0")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_40 () {
    local -a literals=("--reservation=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([12]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="12")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_41 () {
    local -a literals=("--tmp=" "10G")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="1" [0]="0")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_42 () {
    local -a literals=("--nodelist=" ",")
    local -A literal_transitions=()
    literal_transitions[2]="([1]=1)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([13]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([2]="1" [0]="0")
    local -A commands_level_0=([1]="13")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_43 () {
    local -a literals=("--exclude=" ",")
    local -A literal_transitions=()
    literal_transitions[2]="([1]=1)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([13]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([2]="1" [0]="0")
    local -A commands_level_0=([1]="13")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_44 () {
    local -a literals=("--exclusive" "=user")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="1" [0]="0")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_45 () {
    local -a literals=("--exclusive" "=mcs")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="1" [0]="0")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_46 () {
    local -a literals=("--cpus-per-gpu=" "8")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="1" [0]="0")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_47 () {
    local -a literals=("--gpus=" "1")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="1" [0]="0")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_48 () {
    local -a literals=(",")
    local -A literal_transitions=()
    literal_transitions[1]="([0]=0)"
    local -A command_transitions=()
    command_transitions[0]="([13]=1)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="0")
    local -A commands_level_0=([0]="13")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_49 () {
    local -a literals=("minutes" "seconds" "weeks" "hours" "days" "now" "+1")
    local -A literal_transitions=()
    literal_transitions[1]="([6]=2)"
    literal_transitions[0]="([5]=1)"
    literal_transitions[2]="([1]=3 [0]=3 [3]=3 [4]=3 [2]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="6" [0]="5" [2]="1 0 3 4 2")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_50 () {
    local -a literals=("HH:MM" ":SS")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1" [0]="0")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_51 () {
    local -a literals=("YYYY-MM-DD" "THH:MM" ":SS")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[0]="([0]=1)"
    literal_transitions[2]="([2]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([1]="1" [0]="0" [2]="2")
    local -A commands_level_0=()
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_52 () {
    local -a literals=(",")
    local -A literal_transitions=()
    literal_transitions[1]="([0]=0)"
    local -A command_transitions=()
    command_transitions[0]="([13]=1)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="0")
    local -A commands_level_0=([0]="13")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_53 () {
    local -a literals=("afternotok" "aftercorr" "afterany" "afterok" "after" "," ":")
    local -A literal_transitions=()
    literal_transitions[1]="([6]=2)"
    literal_transitions[0]="([4]=1 [2]=1 [3]=1 [1]=1 [0]=1 [5]=0)"
    literal_transitions[3]="([6]=2 [5]=0)"
    local -A command_transitions=()
    command_transitions[2]="([2]=3)"
    local -A literal_transitions_level_0=([1]="6" [0]="4 2 3 1 0 5" [3]="6 5")
    local -A commands_level_0=([2]="2")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_54 () {
    local -a literals=(",")
    local -A literal_transitions=()
    literal_transitions[1]="([0]=0)"
    local -A command_transitions=()
    command_transitions[0]="([11]=1)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="0")
    local -A commands_level_0=([0]="11")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword_55 () {
    local -a literals=(":0" ",")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[3]="([1]=2 [0]=1)"
    local -A command_transitions=()
    command_transitions[2]="([5]=3)"
    command_transitions[0]="([5]=1)"
    local -A literal_transitions_level_0=([1]="1" [3]="1 0")
    local -A commands_level_0=([2]="5" [0]="5")
    local max_fallback_level=0
    local state=0
    _sbatch_subword "$1" "$2"
}

_sbatch_subword () {
    [[ $# -ne 2 ]] && return 1
    local mode=$1
    local word=$2

    local char_index=0
    local matched=0
    local nliterals=${#literals[@]}
    while true; do
        if [[ $char_index -ge ${#word} ]]; then
            matched=1
            break
        fi

        local subword=${word:$char_index}

        if [[ -v "literal_transitions[$state]" ]]; then
            local -A state_transitions=${literal_transitions[$state]}

            for ((literal_id = 0; literal_id < nliterals; literal_id++)); do
                local literal=${literals[$literal_id]}
                if [[ $subword == $literal && -v "state_transitions[$literal_id]" ]]; then
                    state=${state_transitions[$literal_id]}
                    char_index=$((char_index + ${#literal}))
                    continue 2
                fi
                if [[ $literal == $subword* ]]; then
                    break 2
                fi
                if [[ $subword == $literal* && -v "state_transitions[$literal_id]" ]]; then
                    state=${state_transitions[$literal_id]}
                    char_index=$((char_index + ${#literal}))
                    continue 2
                fi
            done
        fi

        if [[ -v "command_transitions[$state]" ]]; then
            local matched_prefix="${word:0:$char_index}"
            local -A state_commands=${command_transitions[$state]}
            for cmd_id in "${!state_commands[@]}"; do
                readarray -t subword_candidates < <(_sbatch_cmd_$cmd_id "$subword" "$matched_prefix" | while read -r f1 _; do echo "$f1"; done)
                if [[ ${#subword_candidates[@]} -gt 0 ]]; then
                    indexes=($(
                        for i in "${!subword_candidates[@]}"; do
                            printf '%s %s %s\n' $i "${#subword_candidates[i]}" "${subword_candidates[i]}"
                        done | sort -nrk2,2 -rk3 | cut -f1 -d' '
                    ))
                    decreasing_length=()
                    for i in "${indexes[@]}" ; do
                        decreasing_length+=("${subword_candidates[i]}")
                    done

                    for candidate in "${decreasing_length[@]}"; do
                        if [[ $candidate == $subword ]]; then
                            match_len=${#candidate}
                            char_index=$((char_index + match_len))
                            state=${state_commands[$cmd_id]}
                            continue 3
                        fi

                        if [[ $candidate == $subword* ]]; then
                            break 3
                        fi

                        if [[ $subword == $candidate* ]]; then
                            match_len=${#candidate}
                            char_index=$((char_index + match_len))
                            state=${state_commands[$cmd_id]}
                            continue 3
                        fi
                    done
                fi
            done
        fi

        break
    done

    if [[ $mode = matches ]]; then
        return $((1 - matched))
    fi

    local matched_prefix="${word:0:$char_index}"
    local completed_prefix="${word:$char_index}"

    local -a subword_candidates=()
    local -a subword_matches=()
    for (( subword_fallback_level=0; subword_fallback_level <= max_fallback_level; subword_fallback_level++ )) {
        eval "local literal_transitions_name=literal_transitions_level_${subword_fallback_level}"
        eval "local -a transitions=(\${$literal_transitions_name[$state]})"
        for literal_id in "${transitions[@]}"; do
            local literal=${literals[$literal_id]}
            subword_candidates+=("$matched_prefix$literal")
        done
        __complgen_match "$matched_prefix$completed_prefix" subword_candidates subword_matches

        eval "local commands_name=commands_level_${subword_fallback_level}"
        eval "local -a transitions=(\${$commands_name[$state]})"
        for command_id in "${transitions[@]}"; do
            readarray -t subword_candidates < <(_sbatch_cmd_$command_id "$completed_prefix" "$matched_prefix" | while read -r f1 _; do echo "$f1"; done)
            local -a filtered_candidates=()
            __complgen_match "$completed_prefix" subword_candidates filtered_candidates
            for item in "${filtered_candidates[@]}"; do
                subword_matches+=("$matched_prefix$item")
            done
        done

        if [[ ${#subword_matches[@]} -gt 0 ]]; then
            matches+=("${subword_matches[@]}")
            break
        fi
    }
    return 0
}

_sbatch () {
    if [[ $(type -t _get_comp_words_by_ref) != function ]]; then
        echo _get_comp_words_by_ref: function not defined.  Make sure the bash-completion system package is installed
        return 1
    fi

    local words cword
    _get_comp_words_by_ref -n "$COMP_WORDBREAKS" words cword

    local -a literals=("--oversubscribe" "--container-id=" "--get-user-env" "--contiguous" "--spread-job" "--overcommit" "--parsable" "--comment=" "YYYY-MM-DD" "--version" "--verbose" "arbitrary" "--no-kill" "MM/DD/YY" "--usage" "--quiet" "--help" "--wait" "cyclic" "--hold" "MMDDYY" "plane" "block" "--" "-V" "-h" "-G" "-x" "-w" "-C" "-W" "-v" "-t" "-s" "-Q" "-q" "-p" "-O" "-o" "-N" "-n" "-m" "-M" "-L" "-k" "-J" "-i" "-H" "-e" "-D" "-d" "-c" "-b" "-A" "-a" "1" "8")
    local -A literal_transitions=()
    literal_transitions[2]="([20]=0 [13]=0 [8]=0)"
    literal_transitions[12]="([54]=0 [53]=1 [52]=2 [51]=3 [7]=0 [1]=0 [50]=4 [49]=5 [48]=7 [2]=0 [47]=0 [19]=0 [46]=7 [45]=8 [44]=0 [12]=0 [43]=9 [42]=10 [41]=11 [40]=12 [55]=0 [39]=12 [38]=7 [37]=0 [5]=0 [36]=13 [6]=0 [35]=14 [34]=0 [15]=0 [33]=0 [0]=0 [4]=0 [32]=2 [31]=0 [10]=0 [30]=0 [17]=0 [3]=0 [29]=15 [28]=16 [27]=17 [26]=18 [25]=0 [16]=0 [14]=0 [24]=0 [9]=0)"
    literal_transitions[0]="([54]=0 [53]=1 [52]=2 [51]=3 [7]=0 [1]=0 [50]=4 [49]=5 [48]=7 [2]=0 [47]=0 [19]=0 [46]=7 [45]=8 [44]=0 [12]=0 [43]=9 [42]=10 [41]=11 [40]=12 [39]=12 [38]=7 [37]=0 [5]=0 [36]=13 [6]=0 [35]=14 [34]=0 [15]=0 [33]=0 [0]=0 [4]=0 [32]=2 [31]=0 [10]=0 [30]=0 [17]=0 [3]=0 [29]=15 [28]=16 [27]=17 [26]=18 [25]=0 [16]=0 [14]=0 [24]=0 [9]=0)"
    literal_transitions[11]="([22]=0 [18]=0 [11]=0 [21]=0)"
    literal_transitions[6]="([23]=19)"
    literal_transitions[18]="([54]=0 [53]=1 [52]=2 [51]=3 [7]=0 [1]=0 [50]=4 [49]=5 [48]=7 [2]=0 [47]=0 [19]=0 [46]=7 [45]=8 [44]=0 [12]=0 [43]=9 [42]=10 [41]=11 [40]=12 [39]=12 [38]=7 [37]=0 [5]=0 [36]=13 [6]=0 [35]=14 [34]=0 [15]=0 [33]=0 [0]=0 [4]=0 [32]=2 [31]=0 [10]=0 [30]=0 [17]=0 [3]=0 [29]=15 [28]=16 [27]=17 [26]=18 [55]=0 [25]=0 [16]=0 [14]=0 [24]=0 [9]=0)"
    literal_transitions[19]="([23]=19)"
    literal_transitions[3]="([54]=0 [53]=1 [52]=2 [51]=3 [56]=0 [7]=0 [1]=0 [50]=4 [49]=5 [48]=7 [2]=0 [47]=0 [19]=0 [46]=7 [45]=8 [44]=0 [12]=0 [43]=9 [42]=10 [41]=11 [40]=12 [39]=12 [38]=7 [37]=0 [5]=0 [36]=13 [6]=0 [35]=14 [34]=0 [15]=0 [33]=0 [0]=0 [4]=0 [32]=2 [31]=0 [10]=0 [30]=0 [17]=0 [3]=0 [29]=15 [28]=16 [27]=17 [26]=18 [25]=0 [16]=0 [14]=0 [24]=0 [9]=0)"
    literal_transitions[8]="([54]=0 [53]=1 [52]=2 [51]=3 [7]=0 [1]=0 [50]=4 [49]=5 [48]=7 [2]=0 [47]=0 [19]=0 [46]=7 [45]=8 [44]=0 [12]=0 [43]=9 [42]=10 [41]=11 [40]=12 [39]=12 [38]=7 [37]=0 [5]=0 [36]=13 [6]=0 [35]=14 [34]=0 [15]=0 [33]=0 [0]=0 [4]=0 [32]=2 [31]=0 [10]=0 [30]=0 [17]=0 [3]=0 [29]=15 [28]=16 [27]=17 [26]=18 [25]=0 [16]=0 [14]=0 [24]=0 [9]=0)"
    local -A command_transitions=()
    command_transitions[1]="([0]=0)"
    command_transitions[13]="([8]=0)"
    command_transitions[0]="([3]=6 [14]=6)"
    command_transitions[7]="([1]=0)"
    command_transitions[6]="([3]=6 [1]=19 [14]=6 [10]=19)"
    command_transitions[10]="([6]=0)"
    command_transitions[5]="([3]=0)"
    command_transitions[12]="([3]=6 [14]=6)"
    command_transitions[3]="([3]=6 [14]=6)"
    command_transitions[14]="([9]=0)"
    command_transitions[18]="([3]=6 [14]=6)"
    command_transitions[19]="([1]=19 [10]=19)"
    command_transitions[8]="([3]=6 [1]=0 [14]=6)"
    local -A subword_transitions
    subword_transitions[0]="([0]=0 [1]=0 [2]=0 [3]=0 [4]=0 [5]=0 [6]=0 [7]=0 [8]=0 [9]=0 [10]=0 [11]=0 [12]=0 [13]=0 [14]=0 [15]=0 [16]=0 [17]=0 [18]=0 [19]=0 [20]=0 [21]=0 [22]=0 [23]=0 [24]=0 [25]=0 [26]=0 [27]=0 [28]=0 [29]=0 [30]=0 [31]=0 [32]=0 [33]=0 [34]=0 [35]=0 [36]=0 [37]=0 [38]=0 [39]=0 [40]=0 [41]=0 [42]=0 [43]=0 [44]=0 [45]=0 [46]=0 [47]=0)"
    subword_transitions[2]="([49]=0 [50]=0 [51]=0)"
    subword_transitions[3]="([0]=0 [1]=0 [2]=0 [3]=0 [4]=0 [5]=0 [6]=0 [7]=0 [8]=0 [9]=0 [10]=0 [11]=0 [12]=0 [13]=0 [14]=0 [15]=0 [16]=0 [17]=0 [18]=0 [19]=0 [20]=0 [21]=0 [22]=0 [23]=0 [24]=0 [25]=0 [26]=0 [27]=0 [28]=0 [29]=0 [30]=0 [31]=0 [32]=0 [33]=0 [34]=0 [35]=0 [36]=0 [37]=0 [38]=0 [39]=0 [40]=0 [41]=0 [42]=0 [43]=0 [44]=0 [45]=0 [46]=0 [47]=0)"
    subword_transitions[4]="([53]=0)"
    subword_transitions[8]="([0]=0 [1]=0 [2]=0 [3]=0 [4]=0 [5]=0 [6]=0 [7]=0 [8]=0 [9]=0 [10]=0 [11]=0 [12]=0 [13]=0 [14]=0 [15]=0 [16]=0 [17]=0 [18]=0 [19]=0 [20]=0 [21]=0 [22]=0 [23]=0 [24]=0 [25]=0 [26]=0 [27]=0 [28]=0 [29]=0 [30]=0 [31]=0 [32]=0 [33]=0 [34]=0 [35]=0 [36]=0 [37]=0 [38]=0 [39]=0 [40]=0 [41]=0 [42]=0 [43]=0 [44]=0 [45]=0 [46]=0 [47]=0)"
    subword_transitions[9]="([55]=0)"
    subword_transitions[12]="([0]=0 [1]=0 [2]=0 [3]=0 [4]=0 [5]=0 [6]=0 [7]=0 [8]=0 [9]=0 [10]=0 [11]=0 [12]=0 [13]=0 [14]=0 [15]=0 [16]=0 [17]=0 [18]=0 [19]=0 [20]=0 [21]=0 [22]=0 [23]=0 [24]=0 [25]=0 [26]=0 [27]=0 [28]=0 [29]=0 [30]=0 [31]=0 [32]=0 [33]=0 [34]=0 [35]=0 [36]=0 [37]=0 [38]=0 [39]=0 [40]=0 [41]=0 [42]=0 [43]=0 [44]=0 [45]=0 [46]=0 [47]=0)"
    subword_transitions[15]="([54]=0)"
    subword_transitions[16]="([48]=0)"
    subword_transitions[17]="([52]=0)"
    subword_transitions[18]="([0]=0 [1]=0 [2]=0 [3]=0 [4]=0 [5]=0 [6]=0 [7]=0 [8]=0 [9]=0 [10]=0 [11]=0 [12]=0 [13]=0 [14]=0 [15]=0 [16]=0 [17]=0 [18]=0 [19]=0 [20]=0 [21]=0 [22]=0 [23]=0 [24]=0 [25]=0 [26]=0 [27]=0 [28]=0 [29]=0 [30]=0 [31]=0 [32]=0 [33]=0 [34]=0 [35]=0 [36]=0 [37]=0 [38]=0 [39]=0 [40]=0 [41]=0 [42]=0 [43]=0 [44]=0 [45]=0 [46]=0 [47]=0)"

    local state=0
    local word_index=1
    local nliterals=${#literals[@]}
    while [[ $word_index -lt $cword ]]; do
        local word=${words[$word_index]}

        if [[ -v "literal_transitions[$state]" ]]; then
            local -A state_transitions=${literal_transitions[$state]}

            for ((literal_id = 0; literal_id < nliterals; literal_id++)); do
                if [[ ${literals[$literal_id]} = "$word" ]]; then
                    if [[ -v "state_transitions[$literal_id]" ]]; then
                        state=${state_transitions[$literal_id]}
                        word_index=$((word_index + 1))
                        continue 2
                    fi
                fi
            done
        fi

        if [[ -v "subword_transitions[$state]" ]]; then
            local -A state_transitions=${subword_transitions[$state]}

            for subword_id in "${!state_transitions[@]}"; do
                if _sbatch_subword_"${subword_id}" matches "$word"; then
                    state=${state_transitions[$subword_id]}
                    word_index=$((word_index + 1))
                    continue 2
                fi
            done
        fi

        if [[ -v "command_transitions[$state]" ]]; then
            local -A state_commands=${command_transitions[$state]}
            for cmd_id in "${!state_commands[@]}"; do
                readarray -t candidates < <(_sbatch_cmd_$cmd_id "" "" | while read -r f1 _; do echo "$f1"; done)
                if [[ ${#candidates[@]} -gt 0 ]]; then
                    indexes=($(
                        for i in "${!candidates[@]}" ; do
                            printf '%s %s %s\n' $i "${#candidates[i]}" "${candidates[i]}"
                        done | sort -nrk2,2 -rk3 | cut -f1 -d' '
                    ))
                    decreasing_length=()
                    for i in "${indexes[@]}"; do
                        decreasing_length+=("${candidates[i]}")
                    done

                    for candidate in "${decreasing_length[@]}"; do
                        if [[ $candidate == $word ]]; then
                            state=${state_commands[$cmd_id]}
                            word_index=$((word_index + 1))
                            continue 3
                        fi
                    done

                    if [[ $(($word_index + 1)) == $cword ]]; then
                        break 3
                    fi
                fi
            done
        fi

        return 1
    done

    local -A literal_transitions_level_0=([2]="20 13 8" [19]="23" [0]="54 53 52 51 7 1 50 49 48 2 47 19 46 45 44 12 43 42 41 40 39 38 37 5 36 6 35 34 15 33 0 4 32 31 10 30 17" [6]="23" [12]="54 53 52 51 7 1 50 49 48 2 47 19 46 45 44 12 43 42 41 40 55 39 38 37 5 36 6 35 34 15 33 0 4 32 31 10 30 17" [11]="22 18 11 21" [18]="54 53 52 51 7 1 50 49 48 2 47 19 46 45 44 12 43 42 41 40 39 38 37 5 36 6 35 34 15 33 0 4 32 31 10 30 17" [3]="54 53 52 51 56 7 1 50 49 48 2 47 19 46 45 44 12 43 42 41 40 39 38 37 5 36 6 35 34 15 33 0 4 32 31 10 30 17" [8]="54 53 52 51 7 1 50 49 48 2 47 19 46 45 44 12 43 42 41 40 39 38 37 5 36 6 35 34 15 33 0 4 32 31 10 30 17")
    local -A literal_transitions_level_1=([3]="3 29 28 27 26 25 16 14 24 9" [18]="3 29 28 27 26 55 25 16 14 24 9" [0]="3 29 28 27 26 25 16 14 24 9" [12]="3 29 28 27 26 25 16 14 24 9" [8]="3 29 28 27 26 25 16 14 24 9")
    local -A commands_level_0=([1]="0" [14]="9" [0]="3 14" [12]="3 14" [13]="8" [6]="3 1 14 10" [5]="3" [19]="1 10" [3]="3 14" [7]="1" [10]="6" [18]="3 14" [8]="3 1 14")
    local -A commands_level_1=()
    local -A subword_transitions_level_0=([18]="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34" [2]="49 50 51" [0]="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34" [12]="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34" [4]="53" [9]="55" [3]="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34" [8]="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34")
    local -A subword_transitions_level_1=([18]="35 36 37 38 39 40 41 42 43 44 45 46 47" [0]="35 36 37 38 39 40 41 42 43 44 45 46 47" [12]="35 36 37 38 39 40 41 42 43 44 45 46 47" [17]="52" [16]="48" [15]="54" [3]="35 36 37 38 39 40 41 42 43 44 45 46 47" [8]="35 36 37 38 39 40 41 42 43 44 45 46 47")

    local ignore_case=$(bind -v | while read -r _ var value; do [[ $var = completion-ignore-case ]] && echo $value; done)
    if [[ $ignore_case = on ]]; then
        __complgen_match () {
            [[ $# -lt 3 ]] && return 1
            local prefix=$1
            declare -n candidates_=$2
            declare -n matches_=$3
            if [[ -z $prefix ]]; then
                matches_+=("${candidates_[@]}")
            else
                prefix=${prefix,,}
                prefix=$(printf '%q' "$prefix")
                for line in "${candidates_[@]}"; do
                    [[ ${line,,} = ${prefix}* ]] && matches_+=("$line")
                done
            fi
        }
    else
        __complgen_match () {
            [[ $# -lt 3 ]] && return 1
            local prefix=$1
            declare -n candidates_=$2
            declare -n matches_=$3
            if [[ -z $prefix ]]; then
                matches_+=("${candidates_[@]}")
            else
                prefix=$(printf '%q' "$prefix")
                for line in "${candidates_[@]}"; do
                    [[ $line = ${prefix}* ]] && matches_+=("$line")
                done
            fi
        }
    fi


    local -a candidates=()
    local -a matches=()
    local max_fallback_level=1
    local prefix="${words[$cword]}"
    for (( fallback_level=0; fallback_level <= max_fallback_level; fallback_level++ )) {
        eval "local literal_transitions_name=literal_transitions_level_${fallback_level}"
        eval "local -a transitions=(\${$literal_transitions_name[$state]})"
        for literal_id in "${transitions[@]}"; do
            local literal="${literals[$literal_id]}"
            candidates+=("$literal ")
        done
        if [[ ${#candidates[@]} -gt 0 ]]; then
            __complgen_match "$prefix" candidates matches
        fi
        eval "local subword_transitions_name=subword_transitions_level_${fallback_level}"
        eval "local -a transitions=(\${$subword_transitions_name[$state]})"
        for subword_id in "${transitions[@]}"; do
            _sbatch_subword_$subword_id complete "$prefix"
        done
        eval "local commands_name=commands_level_${fallback_level}"
        eval "local -a transitions=(\${$commands_name[$state]})"
        for command_id in "${transitions[@]}"; do
            readarray -t candidates < <(_sbatch_cmd_$command_id "$prefix" "" | while read -r f1 _; do echo "$f1"; done)
            if [[ ${#candidates[@]} -gt 0 ]]; then
                __complgen_match "$prefix" candidates matches
            fi
        done
        if [[ ${#matches[@]} -gt 0 ]]; then
            local shortest_suffix="$prefix"
            for ((i=0; i < ${#COMP_WORDBREAKS}; i++)); do
                local char="${COMP_WORDBREAKS:$i:1}"
                local candidate=${prefix##*$char}
                if [[ ${#candidate} -lt ${#shortest_suffix} ]]; then
                    shortest_suffix=$candidate
                fi
            done
            local superfluous_prefix=""
            if [[ "$shortest_suffix" != "$prefix" ]]; then
                local superfluous_prefix=${prefix%$shortest_suffix}
            fi
            COMPREPLY=("${matches[@]#$superfluous_prefix}")
            break
        fi
    }

    return 0
}

complete -o nospace -F _sbatch sbatch
