# scancel completion script generated by https://github.com/adaszko/complgen
function _scancel_cmd_0
    set 1 $argv[1]
    squeue -u $USER -ho '%A|%j|%T' | tr -s '|' '\t'
end

function _scancel_cmd_1
    set 1 $argv[1]
    sacctmgr show account -nP format=account
end

function _scancel_cmd_2
    set 1 $argv[1]
    squeue -u $USER -ho '%j|%T' | tr -s '|' '\t'
end

function _scancel_cmd_3
    set 1 $argv[1]
    sinfo -ho '%P'
end

function _scancel_cmd_4
    set 1 $argv[1]
    sacctmgr show qos -nP format=name
end

function _scancel_cmd_5
    set 1 $argv[1]
    sacctmgr show reservation -nP format=name
end

function _scancel_cmd_6
    set 1 $argv[1]
    sacctmgr show cluster -nP format=clusters
end

function _scancel_cmd_7
    set 1 $argv[1]
    sacctmgr show user -nP format=user
end

function _scancel_cmd_8
    set 1 $argv[1]
    squeue -u $USER -ho '%w'
end

function _scancel_subword_1
    set mode $argv[1]
    set word $argv[2]

    set --global subword_literals "--account="
    set --global subword_descrs
    set --global subword_descrs[1] "act only on jobs charging this account"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "1,3"

    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 1
    set --global subword_literal_inputs_level_1 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "1"
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1

    set --global subword_state 1
    _scancel_subword "$mode" "$word"
end


function _scancel_subword_2
    set mode $argv[1]
    set word $argv[2]

    set --global subword_literals "--jobname="
    set --global subword_descrs
    set --global subword_descrs[1] "act only on jobs with this name"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "2,3"

    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 1
    set --global subword_literal_inputs_level_1 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "2"
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1

    set --global subword_state 1
    _scancel_subword "$mode" "$word"
end


function _scancel_subword_3
    set mode $argv[1]
    set word $argv[2]

    set --global subword_literals "--name="
    set --global subword_descrs
    set --global subword_descrs[1] "act only on jobs with this name"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "2,3"

    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 1
    set --global subword_literal_inputs_level_1 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "2"
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1

    set --global subword_state 1
    _scancel_subword "$mode" "$word"
end


function _scancel_subword_4
    set mode $argv[1]
    set word $argv[2]

    set --global subword_literals "--partition="
    set --global subword_descrs
    set --global subword_descrs[1] "act only on jobs in this partition"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "3,3"

    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 1
    set --global subword_literal_inputs_level_1 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "3"
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1

    set --global subword_state 1
    _scancel_subword "$mode" "$word"
end


function _scancel_subword_5
    set mode $argv[1]
    set word $argv[2]

    set --global subword_literals "--qos="
    set --global subword_descrs
    set --global subword_descrs[1] "act only on jobs with this quality of service"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "4,3"

    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 1
    set --global subword_literal_inputs_level_1 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "4"
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1

    set --global subword_state 1
    _scancel_subword "$mode" "$word"
end


function _scancel_subword_6
    set mode $argv[1]
    set word $argv[2]

    set --global subword_literals "--reservation="
    set --global subword_descrs
    set --global subword_descrs[1] "act only on jobs with this reservation"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "5,3"

    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 1
    set --global subword_literal_inputs_level_1 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "5"
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1

    set --global subword_state 1
    _scancel_subword "$mode" "$word"
end


function _scancel_subword_7
    set mode $argv[1]
    set word $argv[2]

    set --global subword_literals "--sibling="
    set --global subword_descrs
    set --global subword_descrs[1] "remove an active sibling job from a federated job"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "6,3"

    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 1
    set --global subword_literal_inputs_level_1 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "6"
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1

    set --global subword_state 1
    _scancel_subword "$mode" "$word"
end


function _scancel_subword_8
    set mode $argv[1]
    set word $argv[2]

    set --global subword_literals "SIGWAITING" "SIGVTALRM" "--signal=" "SIGWINCH" "SIGXFSZ" "SIGXCPU" "SIGPROF" "SIGTTOU" "SIGTTIN" "SIGCONT" "SIGTSTP" "SIGSTOP" "SIGPOLL" "SIGCHLD" "SIGUSR2" "SIGUSR1" "SIGTERM" "SIGALRM" "SIGPIPE" "SIGSEGV" "SIGKILL" "SIGABRT" "SIGTRAP" "SIGQUIT" "SIGAIO" "SIGLWP" "SIGURG" "SIGPWR" "SIGCLD" "SIGSYS" "SIGBUS" "SIGFPE" "SIGEMT" "SIGIOT" "SIGILL" "SIGINT" "SIGHUP" "SIGIO" "34" "33" "32" "31" "30" "29" "28" "27" "26" "25" "24" "23" "22" "21" "20" "19" "18" "17" "16" "15" "14" "13" "12" "11" "10" "9" "8" "7" "6" "5" "4" "3" "2" "1"
    set --global subword_descrs
    set --global subword_descrs[1] "signal to send to job, default is SIGKILL"
    set --global subword_descr_literal_ids 3
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[2] "72 37 71 36 70 24 69 35 68 23 67 34 22 66 33 65 32 64 21 63 31 62 20 61 30 60 19 59 18 58 17 57 16 56 15 55 29 14 54 28 53 4 52 27 51 13 38 50 12 49 11 48 10 47 9 46 8 45 2 44 7 43 6 42 5 41 1 40 26 39 25"
    set --global subword_literal_transitions_tos[2] "3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3"
    set --global subword_literal_transitions_inputs[1] "3"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions

    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 2 1
    set --global subword_literal_inputs_level_1 "72 37 71 36 70 24 69 35 68 23 67 34 22 66 33 65 32 64 21 63 31 62 20 61 30 60 19 59 18 58 17 57 16 56 15 55 29 14 54 28 53 4 52 27 51 13 38 50 12 49 11 48 10 47 9 46 8 45 2 44 7 43 6 42 5 41 1 40 26 39 25" "3"
    set --global subword_command_froms_level_0 
    set --global subword_commands_level_0 
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1

    set --global subword_state 1
    _scancel_subword "$mode" "$word"
end


function _scancel_subword_9
    set mode $argv[1]
    set word $argv[2]

    set --global subword_literals "SUSPENDED" "--state=" "RUNNING" "PENDING"
    set --global subword_descrs
    set --global subword_descrs[1] "act only on jobs in this state"
    set --global subword_descr_literal_ids 2
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[2] "4 3 1"
    set --global subword_literal_transitions_tos[2] "3 3 3"
    set --global subword_literal_transitions_inputs[1] "2"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions

    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 2 1
    set --global subword_literal_inputs_level_1 "4 3 1" "2"
    set --global subword_command_froms_level_0 
    set --global subword_commands_level_0 
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1

    set --global subword_state 1
    _scancel_subword "$mode" "$word"
end


function _scancel_subword_10
    set mode $argv[1]
    set word $argv[2]

    set --global subword_literals "--user="
    set --global subword_descrs
    set --global subword_descrs[1] "act only on jobs of this user"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "7,3"

    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 1
    set --global subword_literal_inputs_level_1 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "7"
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1

    set --global subword_state 1
    _scancel_subword "$mode" "$word"
end


function _scancel_subword_11
    set mode $argv[1]
    set word $argv[2]

    set --global subword_literals "--wckey="
    set --global subword_descrs
    set --global subword_descrs[1] "act only on jobs with this workload charactization key"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "8,3"

    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 1
    set --global subword_literal_inputs_level_1 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "8"
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1

    set --global subword_state 1
    _scancel_subword "$mode" "$word"
end


function __complgen_match
    set prefix $argv[1]

    set candidates
    set descriptions
    while read c
        set a (string split --max 1 -- "	" $c)
        set --append candidates $a[1]
        if set --query a[2]
            set --append descriptions $a[2]
        else
            set --append descriptions ""
        end
    end

    if test -z "$candidates"
        return 1
    end

    set escaped_prefix (string escape --style=regex -- $prefix)
    set regex "^$escaped_prefix.*"

    set matches_case_sensitive
    set descriptions_case_sensitive
    for i in (seq 1 (count $candidates))
        if string match --regex --quiet --entire -- $regex $candidates[$i]
            set --append matches_case_sensitive $candidates[$i]
            set --append descriptions_case_sensitive $descriptions[$i]
        end
    end

    if set --query matches_case_sensitive[1]
        for i in (seq 1 (count $matches_case_sensitive))
            printf '%s	%s\n' $matches_case_sensitive[$i] $descriptions_case_sensitive[$i]
        end
        return 0
    end

    set matches_case_insensitive
    set descriptions_case_insensitive
    for i in (seq 1 (count $candidates))
        if string match --regex --quiet --ignore-case --entire -- $regex $candidates[$i]
            set --append matches_case_insensitive $candidates[$i]
            set --append descriptions_case_insensitive $descriptions[$i]
        end
    end

    if set --query matches_case_insensitive[1]
        for i in (seq 1 (count $matches_case_insensitive))
            printf '%s	%s\n' $matches_case_insensitive[$i] $descriptions_case_insensitive[$i]
        end
        return 0
    end

    return 1
end

function _scancel_subword
    set mode $argv[1]
    set word $argv[2]

    set char_index 1
    set matched 0
    while true
        if test $char_index -gt (string length -- "$word")
            set matched 1
            break
        end

        set subword (string sub --start=$char_index -- "$word")

        if set --query subword_literal_transitions_inputs[$subword_state] && test -n $subword_literal_transitions_inputs[$subword_state]
            set inputs (string split ' ' $subword_literal_transitions_inputs[$subword_state])
            set tos (string split ' ' $subword_literal_transitions_tos[$subword_state])

            set stop_matching 0
            set literal_matched 0
            for literal_id in (seq 1 (count $subword_literals))
                set literal $subword_literals[$literal_id]
                if test $subword = $literal
                    set index (contains --index -- "$literal_id" $inputs)
                    set subword_state $tos[$index]
                    set literal_len (string length -- "$literal")
                    set char_index (math $char_index + $literal_len)
                    set literal_matched 1
                    break
                end
                if string match --quiet -- "$subword*" $literal
                    set stop_matching 1
                    break
                end
                if string match --quiet -- "$literal*" $subword
                    set index (contains --index -- "$literal_id" $inputs)
                    set subword_state $tos[$index]
                    set literal_len (string length -- "$literal")
                    set char_index (math $char_index + $literal_len)
                    set literal_matched 1
                    break
                end
            end
            if test $stop_matching -ne 0
                break
            end
            if test $literal_matched -ne 0
                continue
            end
        end
        if set --query subword_command_transitions[$subword_state] && test -n $subword_command_transitions[$subword_state]
            set state_transitions (string split ' ' $subword_command_transitions[$subword_state])
            set command_matched 0
            set matched 0
            for cmd_to in $state_transitions
                set fields (string split ',' $cmd_to)
                set cmd_id $fields[1]
                set to $fields[2]
                set function_name _scancel_cmd_$cmd_id
                set candidates ($function_name "" "")
                for i in (seq 1 (count $candidates))
                    set candidate_description (string split --max 1 -- "	" $candidates[$i])
                    set candidates[$i] $candidate_description[1]
                end
                set indexes (
                    for i in (seq 1 (count $candidates))
                        printf '%s %s %s\n' $i (string length -- $candidates[$i]) $candidates[$i]
                    end | sort -nrk2,2 -rk3 | cut -f1 -d' '
                )
                set decreasing_length (for i in $indexes; echo $candidates[$i]; end)

                for candidate in $decreasing_length
                    if test $candidate = $subword
                        set subword_state $to
                        set match_len (string length -- $candidate)
                        set char_index (math $char_index + $match_len)
                        set command_matched 1
                        break
                    end

                    if string match --quiet -- "$subword*" $candidate
                        set command_matched 1
                        set matched 1
                        break
                    end

                    if string match --quiet -- "$candidate*" $subword
                        set subword_state $to
                        set match_len (string length -- $candidate)
                        set char_index (math $char_index + $match_len)
                        set command_matched 1
                        break
                    end
                end
                if test $command_matched -ne 0
                    break
                end
            end
            if test $matched -ne 0
                break
            end
            if test $command_matched -ne 0
                continue
            end
        end

        break
    end

    if test $mode = matches
        return (math 1 - $matched)
    end

    set completed_prefix (string sub --start=$char_index -- $word)

    set matched_prefix
    if test $char_index -eq 1
        set matched_prefix ""
    else
        set matched_prefix (string sub --end=(math $char_index - 1) -- "$word")
    end

    for fallback_level in (seq 0 $subword_max_fallback_level)
        set candidates
        set froms_name subword_literal_froms_level_$fallback_level
        set froms (string split ' ' $$froms_name)
        if contains $subword_state $froms
            set index (contains --index -- "$subword_state" $froms)
            set transitions_name subword_literal_inputs_level_$fallback_level
            set transitions (string split ' ' $$transitions_name[1][$index])
            for literal_id in $transitions
                set completed_prefix_len (string length -- $completed_prefix)
                if test $completed_prefix_len -gt 0
                    set literal $subword_literals[$literal_id]
                    set slice (string sub --end=$completed_prefix_len -- $literal)
                    if test "$slice" != "$completed_prefix"
                        continue
                    end
                end
                set subword_descr_index (contains --index -- "$literal_id" $subword_descr_literal_ids)
                if test -n "$subword_descr_index"
                    set --append candidates (printf '%s%s\t%s\n' $matched_prefix $subword_literals[$literal_id] $subword_descrs[$subword_descr_ids[$subword_descr_index]])
                else
                    set --append candidates (printf '%s%s\n' $matched_prefix $subword_literals[$literal_id])
                end
            end
        end
        set froms_name subword_command_froms_level_$fallback_level
        set froms (string split ' ' $$froms_name)
        set index (contains --index -- "$subword_state" $froms)
        if test -n "$index"
            set subword_commands_level_name subword_commands_level_$fallback_level
            set function_id $$subword_commands_level_name[1][$index]
            set function_name _scancel_cmd_$function_id
            $function_name "$completed_prefix" "$matched_prefix" | while read line
                set --append candidates (printf '%s%s\n' $matched_prefix $line)
            end
        end
        printf '%s\n' $candidates | __complgen_match && break
    end
end


function _scancel
    set COMP_LINE (commandline --cut-at-cursor)

    set COMP_WORDS
    echo $COMP_LINE | read --tokenize --array COMP_WORDS
    if string match --quiet --regex '.*\s$' $COMP_LINE
        set COMP_CWORD (math (count $COMP_WORDS) + 1)
    else
        set COMP_CWORD (count $COMP_WORDS)
    end

    set literals "--interactive" "--nodelist" "SIGWAITING" "--clusters" "--verbose" "--version" "SUSPENDED" "SIGVTALRM" "SIGWINCH" "--usage" "RUNNING" "PENDING" "SIGXFSZ" "SIGXCPU" "SIGPROF" "SIGTTOU" "SIGTTIN" "SIGCONT" "SIGTSTP" "SIGSTOP" "SIGPOLL" "SIGCHLD" "SIGUSR2" "SIGUSR1" "SIGTERM" "SIGALRM" "SIGPIPE" "SIGSEGV" "SIGKILL" "SIGABRT" "SIGTRAP" "SIGQUIT" "--quiet" "--hurry" "--batch" "--help" "SIGAIO" "SIGLWP" "SIGURG" "SIGPWR" "SIGCLD" "SIGSYS" "SIGBUS" "SIGFPE" "SIGEMT" "SIGIOT" "SIGILL" "SIGINT" "SIGHUP" "--full" "--cron" "--ctld" "SIGIO" "-w" "-v" "-V" "-u" "-t" "34" "33" "32" "31" "30" "29" "28" "27" "26" "25" "24" "23" "22" "21" "20" "19" "18" "17" "16" "15" "14" "13" "12" "11" "10" "-s" "-R" "-q" "-Q" "-p" "-n" "-M" "-i" "-H" "-f" "-c" "-b" "-A" "9" "8" "7" "6" "5" "4" "3" "2" "1"
    set descrs
    set descrs[1] "require response from user for each job"
    set descrs[2] "act only on jobs on these nodes"
    set descrs[3] "clusters to issue commands to"
    set descrs[4] "verbosity level"
    set descrs[5] "output version information and exit"
    set descrs[6] "display brief usage message"
    set descrs[7] "disable warnings"
    set descrs[8] "avoid burst buffer stage out"
    set descrs[9] "signal batch shell for specified job"
    set descrs[10] "show this help message"
    set descrs[11] "signal batch shell and all steps for specified job"
    set descrs[12] "cancel an scrontab job"
    set descrs[13] "send request directly to slurmctld"
    set descrs[14] "act only on jobs of this user"
    set descrs[15] "act only on jobs in this state"
    set descrs[16] "signal to send to job, default is SIGKILL"
    set descrs[17] "act only on jobs with this reservation"
    set descrs[18] "act only on jobs with this quality of service"
    set descrs[19] "act only on jobs in this partition"
    set descrs[20] "act only on jobs with this name"
    set descrs[21] "act only on jobs charging this account"
    set descr_literal_ids 1 2 4 5 6 10 33 34 35 36 50 51 52 54 55 56 57 58 84 85 86 87 88 89 90 91 92 93 94 95 96
    set descr_ids 1 2 3 4 5 6 7 8 9 10 11 12 13 2 4 5 14 15 16 17 18 7 19 20 3 1 8 11 12 9 21
    set literal_transitions_inputs
    set literal_transitions_inputs[1] "96 95 35 52 94 51 93 50 92 34 91 1 90 4 89 88 87 33 86 85 84 58 57 56 6 55 5 54 2 36 10"
    set literal_transitions_tos[1] "2 1 1 1 1 1 1 1 1 1 1 1 3 3 4 5 1 1 6 7 8 9 10 1 1 1 1 1 1 1 1"
    set literal_transitions_inputs[8] "105 49 104 48 103 32 102 47 101 31 100 46 30 99 45 98 44 97 29 83 43 82 28 81 42 80 27 79 26 78 25 77 24 76 23 75 41 22 74 40 73 9 72 39 71 21 53 70 20 69 19 68 18 67 17 66 16 65 8 64 15 63 14 62 13 61 3 60 38 59 37"
    set literal_transitions_tos[8] "1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1"
    set literal_transitions_inputs[9] "12 11 7"
    set literal_transitions_tos[9] "1 1 1"
    set command_transitions
    set command_transitions[2] "1,1"
    set command_transitions[3] "6,1"
    set command_transitions[1] "0,1"
    set command_transitions[7] "5,1"
    set command_transitions[6] "4,1"
    set command_transitions[5] "3,1"
    set command_transitions[4] "2,1"
    set command_transitions[10] "7,1"
    set subword_transitions_ids[1] "1 2 3 4 5 6 7 8 9 10 11"
    set subword_transitions_tos[1] "1 1 1 1 1 1 1 1 1 1 1"

    set state 1
    set word_index 2
    while test $word_index -lt $COMP_CWORD
        set -- word $COMP_WORDS[$word_index]

        if set --query literal_transitions_inputs[$state] && test -n $literal_transitions_inputs[$state]
            set inputs (string split ' ' $literal_transitions_inputs[$state])
            set tos (string split ' ' $literal_transitions_tos[$state])

            set literal_id (contains --index -- "$word" $literals)
            if test -n "$literal_id"
                set index (contains --index -- "$literal_id" $inputs)
                set state $tos[$index]
                set word_index (math $word_index + 1)
                continue
            end
        end

        if set --query subword_transitions_ids[$state] && test -n $subword_transitions_ids[$state]
            set subword_ids (string split ' ' $subword_transitions_ids[$state])
            set tos (string split ' ' $subword_transitions_tos[$state])

            set subword_matched 0
            for subword_id in $subword_ids
                if _scancel_subword_$subword_id matches "$word"
                    set subword_matched 1
                    set state $tos[$subword_id]
                    set word_index (math $word_index + 1)
                    break
                end
            end
            if test $subword_matched -ne 0
                continue
            end
        end

        if set --query command_transitions[$state] && test -n $command_transitions[$state]
            set state_transitions (string split ' ' $command_transitions[$state])
            set command_matched 0
            set matched 0
            for cmd_to in $state_transitions
                set fields (string split ',' $cmd_to)
                set cmd_id $fields[1]
                set to $fields[2]
                set function_name _scancel_cmd_$cmd_id
                set candidates ($function_name "" "")
                for i in (seq 1 (count $candidates))
                    set candidate_description (string split --max 1 -- "	" $candidates[$i])
                    set candidates[$i] $candidate_description[1]
                end
                set indexes (
                    for i in (seq 1 (count $candidates))
                        printf '%s %s %s\n' $i (string length -- $candidates[$i]) $candidates[$i]
                    end | sort -nrk2,2 -rk3 | cut -f1 -d' '
                )
                set decreasing_length (for i in $indexes; echo $candidates[$i]; end)

                for candidate in $decreasing_length
                    if test $candidate = $word
                        set state $to
                        set word_index (math $word_index + 1)
                        set command_matched 1
                        break
                    end
                end
                if test $command_matched -ne 0
                    break
                end

                if test (math $word_index + 1) = $COMP_CWORD
                    set command_matched 1
                    set matched 1
                    break
                end
            end
            if test $matched -ne 0
                break
            end
            if test $command_matched -ne 0
                continue
            end
        end

        return 1
    end

    set literal_froms_level_0 
    set literal_inputs_level_0 
    set literal_froms_level_1 1 8 9
    set literal_inputs_level_1 "96 95 35 52 94 51 93 50 92 34 91 1 90 4 89 88 87 33 86 85 84 58 57 56 6 55 5 54 2 36 10" "105 49 104 48 103 32 102 47 101 31 100 46 30 99 45 98 44 97 29 83 43 82 28 81 42 80 27 79 26 78 25 77 24 76 23 75 41 22 74 40 73 9 72 39 71 21 53 70 20 69 19 68 18 67 17 66 16 65 8 64 15 63 14 62 13 61 3 60 38 59 37" "12 11 7"
    set command_froms_level_0 2 3 1 7 6 5 4 10
    set commands_level_0 "1" "6" "0" "5" "4" "3" "2" "7"
    set command_froms_level_1 
    set commands_level_1 
    set subword_froms_level_0 
    set subwords_level_0 
    set subword_froms_level_1 1
    set subwords_level_1 "1 2 3 4 5 6 7 8 9 10 11"

    for fallback_level in (seq 0 1)
        set candidates
        set froms_name literal_froms_level_$fallback_level
        set froms $$froms_name
        set index (contains --index -- "$state" $froms)
        if test -n "$index"
            set level_inputs_name literal_inputs_level_$fallback_level
            set state_inputs (string split ' ' $$level_inputs_name[1][$index])
            for literal_id in $state_inputs
                set descr_index (contains --index -- "$literal_id" $descr_literal_ids)
                if test -n "$descr_index"
                    set --append candidates (printf '%s\t%s\n' $literals[$literal_id] $descrs[$descr_ids[$descr_index]])
                else
                    set --append candidates (printf '%s\n' $literals[$literal_id])
                end
            end
        end

        set subwords_name subword_froms_level_$fallback_level
        set subwords $$subwords_name
        set index (contains --index -- "$state" $subwords)
        if test -n "$index"
            set subwords_name subwords_level_$fallback_level
            set subwords (string split ' ' $$subwords_name)
            for id in $subwords
                set function_name _scancel_subword_$id
                set --append candidates ($function_name complete "$COMP_WORDS[$COMP_CWORD]")
            end
        end

        set commands_name command_froms_level_$fallback_level
        set commands $$commands_name
        set index (contains --index -- "$state" $commands)
        if test -n "$index"
            set commands_name commands_level_$fallback_level
            set commands (string split ' ' $$commands_name)
            set function_id $commands[$index]
            set function_name _scancel_cmd_$function_id
            set --append candidates ($function_name "$COMP_WORDS[$COMP_CWORD]" "")
        end
        printf '%s\n' $candidates | __complgen_match $COMP_WORDS[$word_index] && return 0
    end
end

complete --erase scancel
complete --command scancel --no-files --arguments "(_scancel)"
