# scancel completion script generated by https://github.com/adaszko/complgen

if [[ ${BASH_VERSINFO[0]} -lt 4 ]]; then
    echo "This completion script requires bash 4.0 or newer (current is $BASH_VERSION)"
    exit 1
fi

_scancel_cmd_0 () {
    squeue -u $USER -ho '%A'
}

_scancel_cmd_1 () {
    sacctmgr show account -nP format=account
}

_scancel_cmd_2 () {
    squeue -u $USER -ho '%j'
}

_scancel_cmd_3 () {
    sinfo -ho '%P'
}

_scancel_cmd_4 () {
    sacctmgr show qos -nP format=name
}

_scancel_cmd_5 () {
    sacctmgr show reservation -nP format=name
}

_scancel_cmd_6 () {
    sacctmgr show cluster -nP format=clusters
}

_scancel_cmd_7 () {
    sacctmgr show user -nP format=user
}

_scancel_cmd_8 () {
    squeue -u $USER -ho '%w'
}

_scancel_subword_0 () {
    local -a literals=("--account=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([1]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="1")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _scancel_subword "$1" "$2"
}

_scancel_subword_1 () {
    local -a literals=("--jobname=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([2]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="2")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _scancel_subword "$1" "$2"
}

_scancel_subword_2 () {
    local -a literals=("--name=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([2]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="2")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _scancel_subword "$1" "$2"
}

_scancel_subword_3 () {
    local -a literals=("--partition=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([3]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="3")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _scancel_subword "$1" "$2"
}

_scancel_subword_4 () {
    local -a literals=("--qos=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([4]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="4")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _scancel_subword "$1" "$2"
}

_scancel_subword_5 () {
    local -a literals=("--reservation=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([5]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="5")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _scancel_subword "$1" "$2"
}

_scancel_subword_6 () {
    local -a literals=("--sibling=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([6]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="6")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _scancel_subword "$1" "$2"
}

_scancel_subword_7 () {
    local -a literals=("SIGWAITING" "SIGVTALRM" "--signal=" "SIGWINCH" "SIGXFSZ" "SIGXCPU" "SIGPROF" "SIGTTOU" "SIGTTIN" "SIGCONT" "SIGTSTP" "SIGSTOP" "SIGPOLL" "SIGCHLD" "SIGUSR2" "SIGUSR1" "SIGTERM" "SIGALRM" "SIGPIPE" "SIGSEGV" "SIGKILL" "SIGABRT" "SIGTRAP" "SIGQUIT" "SIGAIO" "SIGLWP" "SIGURG" "SIGPWR" "SIGCLD" "SIGSYS" "SIGBUS" "SIGFPE" "SIGEMT" "SIGIOT" "SIGILL" "SIGINT" "SIGHUP" "SIGIO" "34" "33" "32" "31" "30" "29" "28" "27" "26" "25" "24" "23" "22" "21" "20" "19" "18" "17" "16" "15" "14" "13" "12" "11" "10" "9" "8" "7" "6" "5" "4" "3" "2" "1")
    local -A literal_transitions=()
    literal_transitions[1]="([71]=2 [36]=2 [70]=2 [35]=2 [69]=2 [23]=2 [68]=2 [34]=2 [67]=2 [22]=2 [66]=2 [33]=2 [21]=2 [65]=2 [32]=2 [64]=2 [31]=2 [63]=2 [20]=2 [62]=2 [30]=2 [61]=2 [19]=2 [60]=2 [29]=2 [59]=2 [18]=2 [58]=2 [17]=2 [57]=2 [16]=2 [56]=2 [15]=2 [55]=2 [14]=2 [54]=2 [28]=2 [13]=2 [53]=2 [27]=2 [52]=2 [3]=2 [51]=2 [26]=2 [50]=2 [12]=2 [37]=2 [49]=2 [11]=2 [48]=2 [10]=2 [47]=2 [9]=2 [46]=2 [8]=2 [45]=2 [7]=2 [44]=2 [1]=2 [43]=2 [6]=2 [42]=2 [5]=2 [41]=2 [4]=2 [40]=2 [0]=2 [39]=2 [25]=2 [38]=2 [24]=2)"
    literal_transitions[0]="([2]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="71 36 70 35 69 23 68 34 67 22 66 33 21 65 32 64 31 63 20 62 30 61 19 60 29 59 18 58 17 57 16 56 15 55 14 54 28 13 53 27 52 3 51 26 50 12 37 49 11 48 10 47 9 46 8 45 7 44 1 43 6 42 5 41 4 40 0 39 25 38 24" [0]="2")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _scancel_subword "$1" "$2"
}

_scancel_subword_8 () {
    local -a literals=("SUSPENDED" "--state=" "RUNNING" "PENDING")
    local -A literal_transitions=()
    literal_transitions[1]="([3]=2 [2]=2 [0]=2)"
    literal_transitions[0]="([1]=1)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="3 2 0" [0]="1")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _scancel_subword "$1" "$2"
}

_scancel_subword_9 () {
    local -a literals=("--user=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([7]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="7")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _scancel_subword "$1" "$2"
}

_scancel_subword_10 () {
    local -a literals=("--wckey=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([8]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="8")
    local -A commands_level_1=()
    local max_fallback_level=1
    local state=0
    _scancel_subword "$1" "$2"
}

_scancel_subword () {
    [[ $# -ne 2 ]] && return 1
    local mode=$1
    local word=$2

    local char_index=0
    local matched=0
    local nliterals=${#literals[@]}
    while true; do
        if [[ $char_index -ge ${#word} ]]; then
            matched=1
            break
        fi

        local subword=${word:$char_index}

        if [[ -v "literal_transitions[$state]" ]]; then
            local -A state_transitions=${literal_transitions[$state]}

            for ((literal_id = 0; literal_id < nliterals; literal_id++)); do
                local literal=${literals[$literal_id]}
                if [[ $subword == $literal && -v "state_transitions[$literal_id]" ]]; then
                    state=${state_transitions[$literal_id]}
                    char_index=$((char_index + ${#literal}))
                    continue 2
                fi
                if [[ $literal == $subword* ]]; then
                    break 2
                fi
                if [[ $subword == $literal* && -v "state_transitions[$literal_id]" ]]; then
                    state=${state_transitions[$literal_id]}
                    char_index=$((char_index + ${#literal}))
                    continue 2
                fi
            done
        fi

        if [[ -v "command_transitions[$state]" ]]; then
            local matched_prefix="${word:0:$char_index}"
            local -A state_commands=${command_transitions[$state]}
            for cmd_id in "${!state_commands[@]}"; do
                readarray -t subword_candidates < <(_scancel_cmd_$cmd_id "$subword" "$matched_prefix" | while read -r f1 _; do echo "$f1"; done)
                if [[ ${#subword_candidates[@]} -gt 0 ]]; then
                    indexes=($(
                        for i in "${!subword_candidates[@]}"; do
                            printf '%s %s %s\n' $i "${#subword_candidates[i]}" "${subword_candidates[i]}"
                        done | sort -nrk2,2 -rk3 | cut -f1 -d' '
                    ))
                    decreasing_length=()
                    for i in "${indexes[@]}" ; do
                        decreasing_length+=("${subword_candidates[i]}")
                    done

                    for candidate in "${decreasing_length[@]}"; do
                        if [[ $candidate == $subword ]]; then
                            match_len=${#candidate}
                            char_index=$((char_index + match_len))
                            state=${state_commands[$cmd_id]}
                            continue 3
                        fi

                        if [[ $candidate == $subword* ]]; then
                            break 3
                        fi

                        if [[ $subword == $candidate* ]]; then
                            match_len=${#candidate}
                            char_index=$((char_index + match_len))
                            state=${state_commands[$cmd_id]}
                            continue 3
                        fi
                    done
                fi
            done
        fi

        break
    done

    if [[ $mode = matches ]]; then
        return $((1 - matched))
    fi

    local matched_prefix="${word:0:$char_index}"
    local completed_prefix="${word:$char_index}"

    local -a subword_candidates=()
    local -a subword_matches=()
    for (( subword_fallback_level=0; subword_fallback_level <= max_fallback_level; subword_fallback_level++ )) {
        eval "local literal_transitions_name=literal_transitions_level_${subword_fallback_level}"
        eval "local -a transitions=(\${$literal_transitions_name[$state]})"
        for literal_id in "${transitions[@]}"; do
            local literal=${literals[$literal_id]}
            subword_candidates+=("$matched_prefix$literal")
        done
        __complgen_match "$matched_prefix$completed_prefix" subword_candidates subword_matches

        eval "local commands_name=commands_level_${subword_fallback_level}"
        eval "local -a transitions=(\${$commands_name[$state]})"
        for command_id in "${transitions[@]}"; do
            readarray -t subword_candidates < <(_scancel_cmd_$command_id "$completed_prefix" "$matched_prefix" | while read -r f1 _; do echo "$f1"; done)
            local -a filtered_candidates=()
            __complgen_match "$completed_prefix" subword_candidates filtered_candidates
            for item in "${filtered_candidates[@]}"; do
                subword_matches+=("$matched_prefix$item")
            done
        done

        if [[ ${#subword_matches[@]} -gt 0 ]]; then
            matches+=("${subword_matches[@]}")
            break
        fi
    }
    return 0
}

_scancel () {
    if [[ $(type -t _get_comp_words_by_ref) != function ]]; then
        echo _get_comp_words_by_ref: function not defined.  Make sure the bash-completion system package is installed
        return 1
    fi

    local words cword
    _get_comp_words_by_ref -n "$COMP_WORDBREAKS" words cword

    local -a literals=("--interactive" "--nodelist" "SIGWAITING" "--clusters" "--verbose" "--version" "SUSPENDED" "SIGVTALRM" "SIGWINCH" "--usage" "RUNNING" "PENDING" "SIGXFSZ" "SIGXCPU" "SIGPROF" "SIGTTOU" "SIGTTIN" "SIGCONT" "SIGTSTP" "SIGSTOP" "SIGPOLL" "SIGCHLD" "SIGUSR2" "SIGUSR1" "SIGTERM" "SIGALRM" "SIGPIPE" "SIGSEGV" "SIGKILL" "SIGABRT" "SIGTRAP" "SIGQUIT" "--quiet" "--hurry" "--batch" "--help" "SIGAIO" "SIGLWP" "SIGURG" "SIGPWR" "SIGCLD" "SIGSYS" "SIGBUS" "SIGFPE" "SIGEMT" "SIGIOT" "SIGILL" "SIGINT" "SIGHUP" "--full" "--cron" "--ctld" "SIGIO" "-w" "-v" "-V" "-u" "-t" "34" "33" "32" "31" "30" "29" "28" "27" "26" "25" "24" "23" "22" "21" "20" "19" "18" "17" "16" "15" "14" "13" "12" "11" "10" "-s" "-R" "-q" "-Q" "-p" "-n" "-M" "-i" "-H" "-f" "-c" "-b" "-A" "9" "8" "7" "6" "5" "4" "3" "2" "1")
    local -A literal_transitions=()
    literal_transitions[0]="([95]=1 [94]=0 [34]=0 [51]=0 [93]=0 [50]=0 [92]=0 [49]=0 [91]=0 [33]=0 [90]=0 [0]=0 [89]=2 [3]=2 [88]=3 [87]=4 [86]=0 [32]=0 [85]=5 [84]=6 [83]=7 [57]=8 [56]=9 [55]=0 [5]=0 [54]=0 [4]=0 [53]=0 [1]=0 [35]=0 [9]=0)"
    literal_transitions[7]="([104]=0 [48]=0 [103]=0 [47]=0 [102]=0 [31]=0 [101]=0 [46]=0 [100]=0 [30]=0 [99]=0 [45]=0 [29]=0 [98]=0 [44]=0 [97]=0 [43]=0 [96]=0 [28]=0 [82]=0 [42]=0 [81]=0 [27]=0 [80]=0 [41]=0 [79]=0 [26]=0 [78]=0 [25]=0 [77]=0 [24]=0 [76]=0 [23]=0 [75]=0 [22]=0 [74]=0 [40]=0 [21]=0 [73]=0 [39]=0 [72]=0 [8]=0 [71]=0 [38]=0 [70]=0 [20]=0 [52]=0 [69]=0 [19]=0 [68]=0 [18]=0 [67]=0 [17]=0 [66]=0 [16]=0 [65]=0 [15]=0 [64]=0 [7]=0 [63]=0 [14]=0 [62]=0 [13]=0 [61]=0 [12]=0 [60]=0 [2]=0 [59]=0 [37]=0 [58]=0 [36]=0)"
    literal_transitions[8]="([11]=0 [10]=0 [6]=0)"
    local -A command_transitions=()
    command_transitions[1]="([1]=0)"
    command_transitions[2]="([6]=0)"
    command_transitions[0]="([0]=0)"
    command_transitions[6]="([5]=0)"
    command_transitions[5]="([4]=0)"
    command_transitions[4]="([3]=0)"
    command_transitions[3]="([2]=0)"
    command_transitions[9]="([7]=0)"
    local -A subword_transitions
    subword_transitions[0]="([0]=0 [1]=0 [2]=0 [3]=0 [4]=0 [5]=0 [6]=0 [7]=0 [8]=0 [9]=0 [10]=0)"

    local state=0
    local word_index=1
    local nliterals=${#literals[@]}
    while [[ $word_index -lt $cword ]]; do
        local word=${words[$word_index]}

        if [[ -v "literal_transitions[$state]" ]]; then
            local -A state_transitions=${literal_transitions[$state]}

            for ((literal_id = 0; literal_id < nliterals; literal_id++)); do
                if [[ ${literals[$literal_id]} = "$word" ]]; then
                    if [[ -v "state_transitions[$literal_id]" ]]; then
                        state=${state_transitions[$literal_id]}
                        word_index=$((word_index + 1))
                        continue 2
                    fi
                fi
            done
        fi

        if [[ -v "subword_transitions[$state]" ]]; then
            local -A state_transitions=${subword_transitions[$state]}

            for subword_id in "${!state_transitions[@]}"; do
                if _scancel_subword_"${subword_id}" matches "$word"; then
                    state=${state_transitions[$subword_id]}
                    word_index=$((word_index + 1))
                    continue 2
                fi
            done
        fi

        if [[ -v "command_transitions[$state]" ]]; then
            local -A state_commands=${command_transitions[$state]}
            for cmd_id in "${!state_commands[@]}"; do
                readarray -t candidates < <(_scancel_cmd_$cmd_id "" "" | while read -r f1 _; do echo "$f1"; done)
                if [[ ${#candidates[@]} -gt 0 ]]; then
                    indexes=($(
                        for i in "${!candidates[@]}" ; do
                            printf '%s %s %s\n' $i "${#candidates[i]}" "${candidates[i]}"
                        done | sort -nrk2,2 -rk3 | cut -f1 -d' '
                    ))
                    decreasing_length=()
                    for i in "${indexes[@]}"; do
                        decreasing_length+=("${candidates[i]}")
                    done

                    for candidate in "${decreasing_length[@]}"; do
                        if [[ $candidate == $word ]]; then
                            state=${state_commands[$cmd_id]}
                            word_index=$((word_index + 1))
                            continue 3
                        fi
                    done

                    if [[ $(($word_index + 1)) == $cword ]]; then
                        break 3
                    fi
                fi
            done
        fi

        return 1
    done

    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="95 94 34 51 93 50 92 49 91 33 90 0 89 3 88 87 86 32 85 84 83 57 56 55 5 54 4 53 1 35 9" [7]="104 48 103 47 102 31 101 46 100 30 99 45 29 98 44 97 43 96 28 82 42 81 27 80 41 79 26 78 25 77 24 76 23 75 22 74 40 21 73 39 72 8 71 38 70 20 52 69 19 68 18 67 17 66 16 65 15 64 7 63 14 62 13 61 12 60 2 59 37 58 36" [8]="11 10 6")
    local -A commands_level_0=([1]="1" [2]="6" [0]="0" [6]="5" [5]="4" [4]="3" [3]="2" [9]="7")
    local -A commands_level_1=()
    local -A subword_transitions_level_0=()
    local -A subword_transitions_level_1=([0]="0 1 2 3 4 5 6 7 8 9 10")

    local ignore_case=$(bind -v | while read -r _ var value; do [[ $var = completion-ignore-case ]] && echo $value; done)
    if [[ $ignore_case = on ]]; then
        __complgen_match () {
            [[ $# -lt 3 ]] && return 1
            local prefix=$1
            declare -n candidates_=$2
            declare -n matches_=$3
            if [[ -z $prefix ]]; then
                matches_+=("${candidates_[@]}")
            else
                prefix=${prefix,,}
                prefix=$(printf '%q' "$prefix")
                for line in "${candidates_[@]}"; do
                    [[ ${line,,} = ${prefix}* ]] && matches_+=("$line")
                done
            fi
        }
    else
        __complgen_match () {
            [[ $# -lt 3 ]] && return 1
            local prefix=$1
            declare -n candidates_=$2
            declare -n matches_=$3
            if [[ -z $prefix ]]; then
                matches_+=("${candidates_[@]}")
            else
                prefix=$(printf '%q' "$prefix")
                for line in "${candidates_[@]}"; do
                    [[ $line = ${prefix}* ]] && matches_+=("$line")
                done
            fi
        }
    fi


    local -a candidates=()
    local -a matches=()
    local max_fallback_level=1
    local prefix="${words[$cword]}"
    for (( fallback_level=0; fallback_level <= max_fallback_level; fallback_level++ )) {
        eval "local literal_transitions_name=literal_transitions_level_${fallback_level}"
        eval "local -a transitions=(\${$literal_transitions_name[$state]})"
        for literal_id in "${transitions[@]}"; do
            local literal="${literals[$literal_id]}"
            candidates+=("$literal ")
        done
        if [[ ${#candidates[@]} -gt 0 ]]; then
            __complgen_match "$prefix" candidates matches
        fi
        eval "local subword_transitions_name=subword_transitions_level_${fallback_level}"
        eval "local -a transitions=(\${$subword_transitions_name[$state]})"
        for subword_id in "${transitions[@]}"; do
            _scancel_subword_$subword_id complete "$prefix"
        done
        eval "local commands_name=commands_level_${fallback_level}"
        eval "local -a transitions=(\${$commands_name[$state]})"
        for command_id in "${transitions[@]}"; do
            readarray -t candidates < <(_scancel_cmd_$command_id "$prefix" "" | while read -r f1 _; do echo "$f1"; done)
            if [[ ${#candidates[@]} -gt 0 ]]; then
                __complgen_match "$prefix" candidates matches
            fi
        done
        if [[ ${#matches[@]} -gt 0 ]]; then
            local shortest_suffix="$prefix"
            for ((i=0; i < ${#COMP_WORDBREAKS}; i++)); do
                local char="${COMP_WORDBREAKS:$i:1}"
                local candidate=${prefix##*$char}
                if [[ ${#candidate} -lt ${#shortest_suffix} ]]; then
                    shortest_suffix=$candidate
                fi
            done
            local superfluous_prefix=""
            if [[ "$shortest_suffix" != "$prefix" ]]; then
                local superfluous_prefix=${prefix%$shortest_suffix}
            fi
            COMPREPLY=("${matches[@]#$superfluous_prefix}")
            break
        fi
    }

    return 0
}

complete -o nospace -F _scancel scancel
