# sl completion script generated by https://github.com/adaszko/complgen
function _sl_cmd_0
    set 1 $argv[1]
    squeue -u $USER -ho '%A|%j|%T' | tr -s '|' '\t'
end

function _sl_subword_1
    set mode $argv[1]
    set word $argv[2]

    set --global subword_literals "color," "no-" "--"

    set --global subword_descrs
    set --global subword_descrs[1] "Color output (default: true)"
    set --global subword_descr_literal_ids 3
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[2] "2 1"
    set --global subword_literal_transitions_tos[2] "3 4"
    set --global subword_literal_transitions_inputs[1] "3"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[3] "1"
    set --global subword_literal_transitions_tos[3] "4"

    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 

    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 2 1 3
    set --global subword_literal_inputs_level_1 "2 1" "3" "1"
    set --global subword_max_fallback_level 1

    set --global subword_state 1
    _sl_subword "$mode" "$word"
end


function _sl_subword_2
    set mode $argv[1]
    set word $argv[2]

    set --global subword_literals "stderr," "no-" "--"

    set --global subword_descrs
    set --global subword_descrs[1] "Show stdERR (default: true)"
    set --global subword_descr_literal_ids 3
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[2] "2 1"
    set --global subword_literal_transitions_tos[2] "3 4"
    set --global subword_literal_transitions_inputs[1] "3"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[3] "1"
    set --global subword_literal_transitions_tos[3] "4"

    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 

    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 2 1 3
    set --global subword_literal_inputs_level_1 "2 1" "3" "1"
    set --global subword_max_fallback_level 1

    set --global subword_state 1
    _sl_subword "$mode" "$word"
end


function _sl_subword_3
    set mode $argv[1]
    set word $argv[2]

    set --global subword_literals "stdout," "no-" "--"

    set --global subword_descrs
    set --global subword_descrs[1] "Show stdOUT (default: false)"
    set --global subword_descr_literal_ids 3
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[2] "2 1"
    set --global subword_literal_transitions_tos[2] "3 4"
    set --global subword_literal_transitions_inputs[1] "3"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[3] "1"
    set --global subword_literal_transitions_tos[3] "4"

    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 

    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 2 1 3
    set --global subword_literal_inputs_level_1 "2 1" "3" "1"
    set --global subword_max_fallback_level 1

    set --global subword_state 1
    _sl_subword "$mode" "$word"
end


function _sl_subword_4
    set mode $argv[1]
    set word $argv[2]

    set --global subword_literals "local" "no-" "--"

    set --global subword_descrs
    set --global subword_descrs[1] "Use local or slurm search mode (default: slurm)"
    set --global subword_descr_literal_ids 3
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[2] "2 1"
    set --global subword_literal_transitions_tos[2] "3 4"
    set --global subword_literal_transitions_inputs[1] "3"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[3] "1"
    set --global subword_literal_transitions_tos[3] "4"

    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 

    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 2 1 3
    set --global subword_literal_inputs_level_1 "2 1" "3" "1"
    set --global subword_max_fallback_level 1

    set --global subword_state 1
    _sl_subword "$mode" "$word"
end


function __complgen_match
    set prefix $argv[1]

    set candidates
    set descriptions
    while read c
        set a (string split --max 1 -- "	" $c)
        set --append candidates $a[1]
        if set --query a[2]
            set --append descriptions $a[2]
        else
            set --append descriptions ""
        end
    end

    if test -z "$candidates"
        return 1
    end

    set escaped_prefix (string escape --style=regex -- $prefix)
    set regex "^$escaped_prefix.*"

    set matches_case_sensitive
    set descriptions_case_sensitive
    for i in (seq 1 (count $candidates))
        if string match --regex --quiet --entire -- $regex $candidates[$i]
            set --append matches_case_sensitive $candidates[$i]
            set --append descriptions_case_sensitive $descriptions[$i]
        end
    end

    if set --query matches_case_sensitive[1]
        for i in (seq 1 (count $matches_case_sensitive))
            printf '%s	%s\n' $matches_case_sensitive[$i] $descriptions_case_sensitive[$i]
        end
        return 0
    end

    set matches_case_insensitive
    set descriptions_case_insensitive
    for i in (seq 1 (count $candidates))
        if string match --regex --quiet --ignore-case --entire -- $regex $candidates[$i]
            set --append matches_case_insensitive $candidates[$i]
            set --append descriptions_case_insensitive $descriptions[$i]
        end
    end

    if set --query matches_case_insensitive[1]
        for i in (seq 1 (count $matches_case_insensitive))
            printf '%s	%s\n' $matches_case_insensitive[$i] $descriptions_case_insensitive[$i]
        end
        return 0
    end

    return 1
end

function _sl_subword
    set mode $argv[1]
    set word $argv[2]

    set char_index 1
    set matched 0
    while true
        if test $char_index -gt (string length -- "$word")
            set matched 1
            break
        end

        set subword (string sub --start=$char_index -- "$word")

        if set --query subword_literal_transitions_inputs[$subword_state] && test -n $subword_literal_transitions_inputs[$subword_state]
            set inputs (string split ' ' $subword_literal_transitions_inputs[$subword_state])
            set tos (string split ' ' $subword_literal_transitions_tos[$subword_state])

            set stop_matching 0
            set literal_matched 0
            for literal_id in (seq 1 (count $subword_literals))
                set literal $subword_literals[$literal_id]
                if test $subword = $literal
                    set index (contains --index -- "$literal_id" $inputs)
                    set subword_state $tos[$index]
                    set literal_len (string length -- "$literal")
                    set char_index (math $char_index + $literal_len)
                    set literal_matched 1
                    break
                end
                if string match --quiet -- "$subword*" $literal
                    set stop_matching 1
                    break
                end
                if string match --quiet -- "$literal*" $subword
                    set index (contains --index -- "$literal_id" $inputs)
                    set subword_state $tos[$index]
                    set literal_len (string length -- "$literal")
                    set char_index (math $char_index + $literal_len)
                    set literal_matched 1
                    break
                end
            end
            if test $stop_matching -ne 0
                break
            end
            if test $literal_matched -ne 0
                continue
            end
        end
        set index (contains --index -- "$subword_state" $subword_star_transitions_from)
        if test -n "$index"
            set matched 1
            break
        end

        break
    end

    if test $mode = matches
        return (math 1 - $matched)
    end

    set completed_prefix (string sub --start=$char_index -- $word)

    set matched_prefix
    if test $char_index -eq 1
        set matched_prefix ""
    else
        set matched_prefix (string sub --end=(math $char_index - 1) -- "$word")
    end

    for fallback_level in (seq 0 $subword_max_fallback_level)
        set candidates
        set froms_name subword_literal_froms_level_$fallback_level
        set froms (string split ' ' $$froms_name)
        if contains $subword_state $froms
            set index (contains --index -- "$subword_state" $froms)
            set transitions_name subword_literal_inputs_level_$fallback_level
            set transitions (string split ' ' $$transitions_name[1][$index])
            for literal_id in $transitions
                set completed_prefix_len (string length -- $completed_prefix)
                if test $completed_prefix_len -gt 0
                    set literal $subword_literals[$literal_id]
                    set slice (string sub --end=$completed_prefix_len -- $literal)
                    if test "$slice" != "$completed_prefix"
                        continue
                    end
                end
                set subword_descr_index (contains --index -- "$literal_id" $subword_descr_literal_ids)
                if test -n "$subword_descr_index"
                    set --append candidates (printf '%s%s\t%s\n' $matched_prefix $subword_literals[$literal_id] $subword_descrs[$subword_descr_ids[$subword_descr_index]])
                else
                    set --append candidates (printf '%s%s\n' $matched_prefix $subword_literals[$literal_id])
                end
            end
        end
        printf '%s\n' $candidates | __complgen_match && break
    end
end


function _sl
    set COMP_LINE (commandline --cut-at-cursor)

    set COMP_WORDS
    echo $COMP_LINE | read --tokenize --array COMP_WORDS
    if string match --quiet --regex '.*\s$' $COMP_LINE
        set COMP_CWORD (math (count $COMP_WORDS) + 1)
    else
        set COMP_CWORD (count $COMP_WORDS)
    end

    set literals "--help" "-l" "-o" "-e" "-c" "-h"

    set descrs
    set descrs[1] "Show help message and exit"
    set descrs[2] "Use local or slurm search mode (default: slurm)"
    set descrs[3] "Show stdOUT (default: false)"
    set descrs[4] "Show stdERR (default: true)"
    set descrs[5] "Color output (default: true)"
    set descr_literal_ids 1 2 3 4 5 6
    set descr_ids 1 2 3 4 5 1
    set literal_transitions_inputs
    set literal_transitions_inputs[2] "6 1 5 4 3 2"
    set literal_transitions_tos[2] "2 2 2 2 2 2"
    set literal_transitions_inputs[1] "6 1 5 4 3 2"
    set literal_transitions_tos[1] "2 2 2 2 2 2"
    set command_transitions
    set command_transitions[2] "0,2"
    set command_transitions[1] "0,2"

    set star_transitions_from 
    set star_transitions_to 
    set subword_transitions_ids[1] "1 2 3 4"
    set subword_transitions_tos[1] "2 2 2 2"
    set subword_transitions_ids[2] "1 2 3 4"
    set subword_transitions_tos[2] "2 2 2 2"

    set state 1
    set word_index 2
    while test $word_index -lt $COMP_CWORD
        set -- word $COMP_WORDS[$word_index]

        if set --query literal_transitions_inputs[$state] && test -n $literal_transitions_inputs[$state]
            set inputs (string split ' ' $literal_transitions_inputs[$state])
            set tos (string split ' ' $literal_transitions_tos[$state])

            set literal_id (contains --index -- "$word" $literals)
            if test -n "$literal_id"
                set index (contains --index -- "$literal_id" $inputs)
                set state $tos[$index]
                set word_index (math $word_index + 1)
                continue
            end
        end

        if set --query subword_transitions_ids[$state] && test -n $subword_transitions_ids[$state]
            set subword_ids (string split ' ' $subword_transitions_ids[$state])
            set tos (string split ' ' $subword_transitions_tos[$state])

            set subword_matched 0
            for subword_id in $subword_ids
                if _sl_subword_$subword_id matches "$word"
                    set subword_matched 1
                    set state $tos[$subword_id]
                    set word_index (math $word_index + 1)
                    break
                end
            end
            if test $subword_matched -ne 0
                continue
            end
        end

        if set --query command_transitions[$state] && test -n $command_transitions[$state]
            set state_transitions (string split ' ' $command_transitions[$state])
            set command_matched 0
            set matched 0
            for cmd_to in $state_transitions
                set fields (string split ',' $cmd_to)
                set cmd_id $fields[1]
                set to $fields[2]
                set function_name _sl_cmd_$cmd_id
                set candidates ($function_name "" "")
                for i in (seq 1 (count $candidates))
                    set candidate_description (string split --max 1 -- "	" $candidates[$i])
                    set candidates[$i] $candidate_description[1]
                end
                set indexes (
                    for i in (seq 1 (count $candidates))
                        printf '%s %s %s\n' $i (string length -- $candidates[$i]) $candidates[$i]
                    end | sort -nrk2,2 -rk3 | cut -f1 -d' '
                )
                set decreasing_length (for i in $indexes; echo $candidates[$i]; end)

                for candidate in $decreasing_length
                    if test $candidate = $word
                        set state $to
                        set word_index (math $word_index + 1)
                        set command_matched 1
                        break
                    end
                end
                if test $command_matched -ne 0
                    break
                end

                if test (math $word_index + 1) = $COMP_CWORD
                    set command_matched 1
                    set matched 1
                    break
                end
            end
            if test $matched -ne 0
                break
            end
            if test $command_matched -ne 0
                continue
            end
        end

        set index (contains --index -- "$state" $star_transitions_from)
        if test -n "$index"
            set state $star_transitions_to[$index]
            set word_index (math $word_index + 1)
            continue
        end

        return 1
    end

    set literal_froms_level_0 
    set literal_inputs_level_0 
    set literal_froms_level_1 2 1
    set literal_inputs_level_1 "6 1 5 4 3 2" "6 1 5 4 3 2"
    set command_froms_level_0 2 1
    set commands_level_0 "0" "0"
    set command_froms_level_1 
    set commands_level_1 
    set subword_froms_level_0 
    set subwords_level_0 
    set subword_froms_level_1 2 1
    set subwords_level_1 "1 2 3 4" "1 2 3 4"

    for fallback_level in (seq 0 1)
        set candidates
        set froms_name literal_froms_level_$fallback_level
        set froms $$froms_name
        set index (contains --index -- "$state" $froms)
        if test -n "$index"
            set level_inputs_name literal_inputs_level_$fallback_level
            set state_inputs (string split ' ' $$level_inputs_name[1][$index])
            for literal_id in $state_inputs
                set descr_index (contains --index -- "$literal_id" $descr_literal_ids)
                if test -n "$descr_index"
                    set --append candidates (printf '%s\t%s\n' $literals[$literal_id] $descrs[$descr_ids[$descr_index]])
                else
                    set --append candidates (printf '%s\n' $literals[$literal_id])
                end
            end
        end

        set subwords_name subword_froms_level_$fallback_level
        set subwords $$subwords_name
        set index (contains --index -- "$state" $subwords)
        if test -n "$index"
            set subwords_name subwords_level_$fallback_level
            set subwords (string split ' ' $$subwords_name)
            for id in $subwords
                set function_name _sl_subword_$id
                set --append candidates ($function_name complete "$COMP_WORDS[$COMP_CWORD]")
            end
        end

        set commands_name command_froms_level_$fallback_level
        set commands $$commands_name
        set index (contains --index -- "$state" $commands)
        if test -n "$index"
            set commands_name commands_level_$fallback_level
            set commands (string split ' ' $$commands_name)
            set function_id $commands[$index]
            set function_name _sl_cmd_$function_id
            set --append candidates ($function_name "$COMP_WORDS[$COMP_CWORD]" "")
        end
        printf '%s\n' $candidates | __complgen_match $COMP_WORDS[$word_index] && return 0
    end
end

complete --erase sl
complete --command sl --no-files --arguments "(_sl)"
