# template completion script generated by https://github.com/adaszko/complgen
function _template_cmd_0
    set 1 $argv[1]
    string match -r '.*/.*' $1 && __fish_complete_path "$TEMPLATE_DIR/$1" "Template" | string replace -r "^$TEMPLATE_DIR/" '' | string match -r '^[^/]+/[^/]+\s+.*' || __fish_complete_directories "$TEMPLATE_DIR/$1" | string replace -r "^$TEMPLATE_DIR/" ''
end

function __complgen_match
    set prefix $argv[1]

    set candidates
    set descriptions
    while read c
        set a (string split --max 1 -- "	" $c)
        set --append candidates $a[1]
        if set --query a[2]
            set --append descriptions $a[2]
        else
            set --append descriptions ""
        end
    end

    if test -z "$candidates"
        return 1
    end

    set escaped_prefix (string escape --style=regex -- $prefix)
    set regex "^$escaped_prefix.*"

    set matches_case_sensitive
    set descriptions_case_sensitive
    for i in (seq 1 (count $candidates))
        if string match --regex --quiet --entire -- $regex $candidates[$i]
            set --append matches_case_sensitive $candidates[$i]
            set --append descriptions_case_sensitive $descriptions[$i]
        end
    end

    if set --query matches_case_sensitive[1]
        for i in (seq 1 (count $matches_case_sensitive))
            printf '%s	%s\n' $matches_case_sensitive[$i] $descriptions_case_sensitive[$i]
        end
        return 0
    end

    set matches_case_insensitive
    set descriptions_case_insensitive
    for i in (seq 1 (count $candidates))
        if string match --regex --quiet --ignore-case --entire -- $regex $candidates[$i]
            set --append matches_case_insensitive $candidates[$i]
            set --append descriptions_case_insensitive $descriptions[$i]
        end
    end

    if set --query matches_case_insensitive[1]
        for i in (seq 1 (count $matches_case_insensitive))
            printf '%s	%s\n' $matches_case_insensitive[$i] $descriptions_case_insensitive[$i]
        end
        return 0
    end

    return 1
end


function _template
    set COMP_LINE (commandline --cut-at-cursor)

    set COMP_WORDS
    echo $COMP_LINE | read --tokenize --array COMP_WORDS
    if string match --quiet --regex '.*\s$' $COMP_LINE
        set COMP_CWORD (math (count $COMP_WORDS) + 1)
    else
        set COMP_CWORD (count $COMP_WORDS)
    end

    set literals "--verbose" "--force" "--write" "--help" "-h" "-v" "-f" "-w"
    set descrs
    set descrs[1] "Confirm on write to './<specname>'"
    set descrs[2] "Froce write to './<specname>'"
    set descrs[3] "Write template to './<specname>'"
    set descrs[4] "Print help message"
    set descr_literal_ids 1 2 3 4 5 6 7 8
    set descr_ids 1 2 3 4 4 1 2 3
    set literal_transitions_inputs
    set literal_transitions_inputs[2] "7 2"
    set literal_transitions_tos[2] "3 3"
    set literal_transitions_inputs[1] "8 3 5 4"
    set literal_transitions_tos[1] "2 2 1 1"
    set literal_transitions_inputs[3] "6 1"
    set literal_transitions_tos[3] "1 1"
    set command_transitions
    set command_transitions[1] "0,1"

    set state 1
    set word_index 2
    while test $word_index -lt $COMP_CWORD
        set -- word $COMP_WORDS[$word_index]

        if set --query literal_transitions_inputs[$state] && test -n $literal_transitions_inputs[$state]
            set inputs (string split ' ' $literal_transitions_inputs[$state])
            set tos (string split ' ' $literal_transitions_tos[$state])

            set literal_id (contains --index -- "$word" $literals)
            if test -n "$literal_id"
                set index (contains --index -- "$literal_id" $inputs)
                set state $tos[$index]
                set word_index (math $word_index + 1)
                continue
            end
        end

        if set --query command_transitions[$state] && test -n $command_transitions[$state]
            set state_transitions (string split ' ' $command_transitions[$state])
            set command_matched 0
            set matched 0
            for cmd_to in $state_transitions
                set fields (string split ',' $cmd_to)
                set cmd_id $fields[1]
                set to $fields[2]
                set function_name _template_cmd_$cmd_id
                set candidates ($function_name "" "")
                for i in (seq 1 (count $candidates))
                    set candidate_description (string split --max 1 -- "	" $candidates[$i])
                    set candidates[$i] $candidate_description[1]
                end
                set indexes (
                    for i in (seq 1 (count $candidates))
                        printf '%s %s %s\n' $i (string length -- $candidates[$i]) $candidates[$i]
                    end | sort -nrk2,2 -rk3 | cut -f1 -d' '
                )
                set decreasing_length (for i in $indexes; echo $candidates[$i]; end)

                for candidate in $decreasing_length
                    if test $candidate = $word
                        set state $to
                        set word_index (math $word_index + 1)
                        set command_matched 1
                        break
                    end
                end
                if test $command_matched -ne 0
                    break
                end

                if test (math $word_index + 1) = $COMP_CWORD
                    set command_matched 1
                    set matched 1
                    break
                end
            end
            if test $matched -ne 0
                break
            end
            if test $command_matched -ne 0
                continue
            end
        end

        return 1
    end

    set literal_froms_level_0 
    set literal_inputs_level_0 
    set literal_froms_level_1 2 1 3
    set literal_inputs_level_1 "7 2" "8 3 5 4" "6 1"
    set command_froms_level_0 1
    set commands_level_0 "0"
    set command_froms_level_1 
    set commands_level_1 

    for fallback_level in (seq 0 1)
        set candidates
        set froms_name literal_froms_level_$fallback_level
        set froms $$froms_name
        set index (contains --index -- "$state" $froms)
        if test -n "$index"
            set level_inputs_name literal_inputs_level_$fallback_level
            set state_inputs (string split ' ' $$level_inputs_name[1][$index])
            for literal_id in $state_inputs
                set descr_index (contains --index -- "$literal_id" $descr_literal_ids)
                if test -n "$descr_index"
                    set --append candidates (printf '%s\t%s\n' $literals[$literal_id] $descrs[$descr_ids[$descr_index]])
                else
                    set --append candidates (printf '%s\n' $literals[$literal_id])
                end
            end
        end

        set commands_name command_froms_level_$fallback_level
        set commands $$commands_name
        set index (contains --index -- "$state" $commands)
        if test -n "$index"
            set commands_name commands_level_$fallback_level
            set commands (string split ' ' $$commands_name)
            set function_id $commands[$index]
            set function_name _template_cmd_$function_id
            set --append candidates ($function_name "$COMP_WORDS[$COMP_CWORD]" "")
        end
        printf '%s\n' $candidates | __complgen_match $COMP_WORDS[$word_index] && return 0
    end
end

complete --erase template
complete --command template --no-files --arguments "(_template)"
